### ISSUE TITLE
Steam store sometimes returns cached content

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamdb.info#319]
Which means that some regions either have old discount, or no discount at all, and they won't be updated unless another update is triggered.

A way to fix this could be to queue an app/sub if one of the regions has mismatching discount percentage or something.

**Comment by sharkiller** [comment]
is related to this?
https://steamdb.info/app/271590/
![image](https://cloud.githubusercontent.com/assets/712193/7192812/90417538-e46f-11e4-94b4-99a008f41f1e.png)

**Comment by TomasDuda** [comment]
Currency switch (`?cc=us`) didn't work for a bit, it always loaded the current region, so all updated prices in the timeframe have price set to the EU1 region.

**Comment by xPaw** [comment]
I looked more into this, and Store is returning completely cached content (which includes older app data, asset versions and html content), which means there's some bug in the caching layer (Akamai doing it?) returning older content. This is also the case with just .css/.js files hosted on the CDN as well, when @SteamTracker keeps choking on certain files that keep returning older/newer content.

**Comment by xPaw** [comment]
So that's still a thing. Looked at Akamai's debug headers, and it's returning `TCP_MISS`, so it's a problem on Valve's end.
