### ISSUE TITLE
Display sale page under the sale name

### ISSUE THREAD

**Issue by Uiharu** [SteamDatabase/steamdb.info#350]
If I go to the sales page at this moment I can see there is a "Franchise - Fallout" and then below it says the titles that are on the sale. If I click on the name it goes to that section. It would be nice to have a link to the actual sale page, in case of the fallout sale it would be: store.steampowered.com/sale/fallout/

Or make it a small steam icon like the individual games have. Usually for me it's useful when I am trying to share with friends the whole sale and I have to try to find the sale page.

**Comment by xPaw** [comment]
> Usually for me it's useful when I am trying to share with friends the whole sale and I have to try to find the sale page.

Sale title is clickable, you can use that link to share :)

But yeah, having a link to sale on Steam would be useful too.

**Comment by Uiharu** [comment]
Oh I didn't notice that, well that works then :D
