### ISSUE TITLE
Include release year on sales page

### ISSUE THREAD

**Issue by ghost** [SteamDatabase/steamdb.info#367]
Hello. I have this website bookmarked and visit it every day. It would be amazing if the lists included the release year of the game. Because now I'm pretty much clicking on the links to load the game page and see the release year.

E.g. when it's -80% off for a game released in 2000 or 2015 (or in between) it's really important.

Also adding some icon indicating that the game has Steam trade cards also is important reason to buy the game, especially when it's on sale.

Cheers

**Comment by johndrinkwater** [comment]
Games already show support for trading cards, in their header here: https://steamdb.info/app/570/, the image is https://steamstore-a.akamaihd.net/public/images/v6/ico/ico_cards.png

**Comment by vibrasphere** [comment]
Thanks for reply. I meant in /sales/ page.
