### ISSUE TITLE
"You own this game, click to install" is wrong when app requires ownership of other app

### ISSUE THREAD

**Issue by PowerGamer1** [SteamDatabase/steamdb.info#425]
Games like https://steamdb.info/app/235780/subs/ are displayed as "free" and available for install to anonymous users of the site when it is not the case. In particular, app 235780 requires ownership of app 380 to be installed. See the snippet of app info for app 235780 below:

```
"appinfo"
{
    "appid"     "235780"
    "extended"
    {
        "requiredappid"     "380"
```

**Comment by xPaw** [comment]
It checks `requiredappid` ownership now.
