### ISSUE TITLE
Menu bar seems stuck and doesn't move when zooming in on mobile.

### ISSUE THREAD

**Issue by anticitizen** [SteamDatabase/steamdb.info#441]
Ok, title may be weird but really i don't know how to explain this. So i've taken some screenshots.
If you zoom in on mobile, you can move everything but top header (menu bar).
Here's how it looks if not zoomed in:
http://i.sli.mg/v4fbZr.png

And if you're zooming in, here's what happens:
http://i.sli.mg/VUgjT5.png

This happens with Android web browser. Everyting seems OK with Chrome browser.
If you need any additional information, let me know.

**Comment by xPaw** [comment]
Is this still broken?

**Comment by anticitizen** [comment]
Hello, sorry for this late response. Android browser got a update while ago. I don't know if it was the because of the browser or website, either way problem seems to be gone now.
