### ISSUE TITLE
Latest Update to Steam Reviews

### ISSUE THREAD

**Issue by jimmydorry** [SteamDatabase/steamdb.info#451]
There is new data up for grabs that may be interesting to track, especially for the sales page. You could show the ratio of steam store versus key/gift. It would also be interesting to see what games have the highest percentage of key usage versus store purchases.

http://store.steampowered.com/news/24155/

**DotA2:** ![Dota2](http://i.imgur.com/lYH0o1d.png)

**CS:GO** ![CSGO](http://i.imgur.com/8ytsi8N.png)

**Supraball:** ![Supraball](http://i.imgur.com/u5o4OlE.png)

**30 IMPOSSIBLE LEVELS:** ![30 IMPOSSIBLE LEVELS](http://i.imgur.com/yfByAiB.png)

**GabeN: The Final Decision:** ![GabeN: The Final Decision](http://i.imgur.com/TxohsGQ.png)

**ShipLord:** ![ShipLord](http://i.imgur.com/HZfnENa.png)

**Tea Party Simulator 2015™:** ![Tea Party Simulator 2015™](http://i.imgur.com/ZdZw8yc.png)

**Comment by xPaw** [comment]
To display useful stats (e.g. how many positive reviews are from key activations), we would need to execute multiple http requests to get all the relevant data, and it's not really worth it implementing.
