### ISSUE TITLE
Ability to specify list of appids for /api/GetAppList/

### ISSUE THREAD

**Issue by EhsanKia** [SteamDatabase/steamdb.info#452]
There's currently a simple yet useful api you guys have here:
https://steamdb.info/api/GetAppList/

I know it's not public or supported, but it'd be very useful if you could add a simple parameter for specifying appids (i.e. `appids=440,760,820`) and only get results for those instead of the full list.

**Comment by xPaw** [comment]
There's limited use in having to specify appids in API that gives you the entire list.

**Comment by EhsanKia** [comment]
Well the point would be that you don't get the entire 3mb list but rather only the AppIDs that you need.

That's assuming that the DB is being cached on your service and not just a simple redirection to https://api.steampowered.com/ISteamApps/GetAppList/v2/

**Comment by xPaw** [comment]
That API does not rely on Steam API and uses SteamDB's database.
