### ISSUE TITLE
Packages without website_header_image won't appear on Sales page

### ISSUE THREAD

**Issue by garciabruno** [SteamDatabase/steamdb.info#458]
Packages that don't have a website_header_image won't appear on /sales page being filtered out by a query (Source: Alram)

Example:
Header image returns 404 for this:
http://store.steampowered.com/api/packagedetails/?packageids=91143&cc=USD&l=spanish&v=4

**Comment by Marlamin** [comment]
According to @xPaw this is the only way to filter out useless shit, sadly seems to have a side-effect for things like XCOM in this case, though. Leaving this open so we can have a proper look and think about this in the future.

**Comment by xPaw** [comment]
I fixed this by also considering packages that have more than 1 app in them.
