### ISSUE TITLE
User review counter in Instant search

### ISSUE THREAD

**Issue by thomas-ashcraft** [SteamDatabase/steamdb.info#459]
It's good that we can filter out low rated games. But there is so much trash with nominal high ratings just because they have low amount of reviews. For example, some trash with about 10 good reviews from developers and their friends. So I want to filter out low rated games AND those trash games with less then 100 or 1000 reviews. This would be really useful.

**Comment by xPaw** [comment]
Games with 10 reviews won't have very high ratings due to the algorithm we use.

**Comment by thomas-ashcraft** [comment]
Ok. But there is still huge amount of trash with less then 1000 reviews.

And that option would be useful not just to filter trash out, but to find really high rated games, loved by many people.

**Comment by xPaw** [comment]
We now have a new rating algorithm which is suitable for sorting (amount of reviews is taken into account in the algo), so this is not required.
