### ISSUE TITLE
Why do some games never update on Steam OS Products that are confirmed to work page?

### ISSUE THREAD

**Issue by robertc** [SteamDatabase/steamdb.info#460]
For example these games are all listed as last updated 2 years ago:

![steamos_ _linux_games_ _steam_database_-_2016-11-09_17 17 09](https://cloud.githubusercontent.com/assets/46539/20147495/39674162-a6a0-11e6-9c70-e70ada573282.png)

Many of these games have updated in the last month:
https://steamdb.info/app/326160/history/  
https://steamdb.info/app/268870/history/  
https://steamdb.info/app/331470/history/  
https://steamdb.info/app/286690/history/  
https://steamdb.info/app/257510/history/

**Comment by Tele42** [comment]
Hello @robertc, I'm pretty sure the date listed is when the game was confirmed, and is not "Last Updated."

**Comment by robertc** [comment]
Ah OK, that makes sense.  Is there any way to see a list in order of last updated for the confirmed products?
