### ISSUE TITLE
(Occasionally) app price listing is always inaccurate

### ISSUE THREAD

**Issue by garciabruno** [SteamDatabase/steamdb.info#463]
Price of app id 231430 (Company of Heroes 2) for US on Store is $29.99 USD base price
SteamDB *always* reports $12.99 USD for base price, even on Sales the price is inaccurate..
It might be extracting the price that is shown on the store page for the DLC "British Forces"

This also occurs on a number of apps that I cannot remember at the moment.

**Comment by xPaw** [comment]
`Company of Heroes 2 - The British Forces` ((76411/)[https://steamdb.info/sub/76411/apps/)) grants `Company of Heroes 2` (231430). We check if appid is granted in purchased package to detect prices. In this case, it does, at least in theory.

The DLC appid has a `MustOwnAppToPurchase Company of Heroes 2 (231430)` which I assume blocks the purchase if you don't own the base game yet.

This would be the same issue as #476.

**Comment by xPaw** [comment]
This is fixed now.
