### ISSUE TITLE
[SteamLinux] CommentURL does not display properly on steamdb.info/linux

### ISSUE THREAD

**Issue by Faalagorn** [SteamDatabase/steamdb.info#464]
CommentURL is not displaying correctly on https://steamdb.info/linux/ at least under Chromium (hover under Lifeless Planet to see what I mean) - guess it was supposed to be a clickable link but it displays for me as "Comment||http://example.com/"

Browser: Chromium Version 55.0.2883.87 (64-bit)
OS: Arch Linux

**Comment by xPaw** [comment]
Fixed.
