### ISSUE TITLE
I've found a bug... well hopefully it's a bug.

### ISSUE THREAD

**Issue by Steeldramon** [SteamDatabase/steamdb.info#465]
About 2 months ago my Current account value on the steamdb calculator was over 8000€. Today i've checked it again and it went down to about 2400€. I didn't sell any items... it have become even more. There were no major changes on my account in that time frame... so i assume it has to be a bug.

Another very minor thing, compared to above:
When going through the prices of games Call of Duty: Black Ops II Zombies is shown as it has cost 49.99€, but CoD: Black Ops II at 29.99. Those 2 come as one. I'm marginally annoyed by this, because it's the only game that i have supposedly baught at over 30€.

**Comment by Marlamin** [comment]
I guess that the games you own were discounted in between 2 months ago and now and as such are worth less now.

**Comment by xPaw** [comment]
The value is going to fluctuate a lot, as it uses current game prices. Today the winter sale started, so a lot of games are discounted.

**Comment by Steeldramon** [comment]
Ah ok. Thanks :)
