### ISSUE TITLE
Train Sim only showing 64 DLCS

### ISSUE THREAD

**Issue by aselwyn1** [SteamDatabase/steamdb.info#469]
https://steamdb.info/app/24010/dlc/ only shows the most recent 64 dlcs not all of them any reason for this?

**Comment by xPaw** [comment]
Valve limited it. You can use this though: https://steamdb.info/search/?a=linked&q=24010

**Comment by aselwyn1** [comment]
ah ok thats close enough so the old way thanks :) too bad that page doesn't link the steam store if there still one sale like the other one but at least does the colours for owning and wishlist thanks
