### ISSUE TITLE
No $AUD option

### ISSUE THREAD

**Issue by Skitz24** [SteamDatabase/steamdb.info#470]
In the "_Want to calculate value of your own Steam account?_" section, there is no $AUD option to choose. Not sure if this was intentional, but I feel a little left out. Considering there are 29 currencies listed; including New Zealand (a country smaller than us) you would think the Australian currency would be there.

**Comment by SinZ163** [comment]
SteamDB's stance is that they wont support it until its an option in steam also

**Comment by Skitz24** [comment]
Cheers for the information
