### ISSUE TITLE
the hunter call of wild

### ISSUE THREAD

**Issue by razer460** [SteamDatabase/steamdb.info#474]
getting bad fps  animals are getting stuck and running on the spot

**Comment by Marlamin** [comment]
![image](https://cloud.githubusercontent.com/assets/50212/23057931/b665622a-f4f2-11e6-9337-5700ffd4404a.png)

**Comment by razer460** [comment]
WHY AS IT BEEN CLOSED

**Comment by Marlamin** [comment]
We're not Steam nor have anything to do with whatever you're talking about
