### ISSUE TITLE
OS List for some games seems to be inaccurate/outdated on SteamDB

### ISSUE THREAD

**Issue by Faalagorn** [SteamDatabase/steamdb.info#478]
While browsing [SteamOS & Linux Products on Steam](https://steamdb.info/linux/hints/) I noticed that few of the games listed as "Game Possibly Works" (namely [Dystopia](https://steamdb.info/app/17580/) and [Batla](https://steamdb.info/app/338180/)) do *not* list Steam (or Mac) as OS on Steam Store.
My guess is that the OS was listed at the point of initial scan and the list haven't been updated since.
Either way, it may be worth to look at, as the opposite may be true as well. Unfortunately, if it is based on scrapping the info Steam website (is it?), OS list for removed games may be unavailable, so you may want to take that info account if you decide to do a new scan (should the old info be kept? removed? kept with appropriate note?).

**Comment by xPaw** [comment]
There are at least 3 different OS lists that developers fill in. The oslist site displays comes from the client info, not the store. It's not out of date.
