### ISSUE TITLE
Steamdb "widget" for Firefox always shows N/A players.

### ISSUE THREAD

**Issue by NIKENIT** [SteamDatabase/steamdb.info#480]
http://imgur.com/a/Jq5Rs here is an example, appears on every game's page. If I go to game's page on the steamdb itself, there are players count, no problem. Started several days ago.

Firefox 51.0.1 64bit, SteamDB 1.7.0

**Comment by xPaw** [comment]
Duplicate of https://github.com/SteamDatabase/BrowserExtension/issues/3 should be fixed in next update.
