### ISSUE TITLE
More filtering and sorting options, especially in /sales/

### ISSUE THREAD

**Issue by Lutarisco** [SteamDatabase/steamdb.info#482]
As people is frequently asking for more columns in /sales/, I thought that it'd be a good idea to allow a wider customization when sorting there.

I mean, maybe there's people who'd like to sort the sales by matascore instead of user's.  
Other people want to sort the titles on sale by the original release date.  
And so on...

And I think that the actual sorting method (the classic click-and-arrow) doesn't allow more than one level of sorting. This, being a database with plenty of items with the same values (for example, so many titles with 50% off), should allow that.

I think that all of this could be possible with an expandable section with checkboxes for many columns, with default values, and the modified values being added to the url (e.g. ?columns=metascore,lowestprice would have those columns added to the default ones).  
Then, the sorting thing could work with a list and an ascending-descending checkbox (those where there are many options and only one can be chosen). When an item is selected in such list, another list spawns, letting the user specify the desired sub-order.

Well, this could be reused in an advanced search function, in a personal list, et cetera. But I think what most people ask for right now is such a feature in /sales/.

Keep going with this fantastic and satisfying (in db's terms) project!

**Comment by xPaw** [comment]
> And I think that the actual sorting method (the classic click-and-arrow) doesn't allow more than one level of sorting. This, being a database with plenty of items with the same values (for example, so many titles with 50% off), should allow that.

This is now possible, hold shift when sorting.

**Comment by AgentRev** [comment]
A genre filter in /graph/ would be awesome.

**Comment by mmun** [comment]
I'd love to be able to sort by _how much money I will save_ rather than just by percentage. In fact, I use it so much I wrote a tampermonkey script to do it. :P

PS: Thanks for building this site!

**Comment by oprypin** [comment]
Note that when sorting by "*how much money I will save*" you're just making yourself even more susceptible to shady schemes like "high price, huge sale".

**Comment by xPaw** [comment]
Please create separate issues for each filter option you want, if there are still any.
