### ISSUE TITLE
Player counts on extension has been broken for over one month

### ISSUE THREAD

**Issue by funnelfactory** [SteamDatabase/steamdb.info#485]
Hello,

Using the extension (with Firefox), the player counts for every single game on Steam has been broken for over one month. Could you please fix this problem?

![sdbextissue](https://cloud.githubusercontent.com/assets/26820700/24557017/1990c768-15eb-11e7-9811-cb63974d77b2.png)

Thanks.

**Comment by xPaw** [comment]
An updated version has been pushed to Addons store two months ago already, but Mozilla is yet to review it.

Listed Version: 1.7.0 ?
Next Listed Version: 1.7.2 ?
Last Updated: 19 Feb 2017
Queue Position: 93 of 242
