### ISSUE TITLE
Can't search for null / absent keys

### ISSUE THREAD

**Issue by gh89275** [SteamDatabase/steamdb.info#487]
I wanted to find apps with their community hub hidden or deleted.

I know what key to search for - `community_hub_visible`. But this key is never set to 0. For those unlucky apps, it is simply absent.

AFAICT there is no way to search for this.

I tried [`null`](https://steamdb.info/search/?a=app_keynames&type=1&keyname=375&operator=3&keyvalue=null) and got no results.  
I tried [the empty string](https://steamdb.info/search/?a=app_keynames&type=1&keyname=375&operator=3&keyvalue=) and got the whole database returned!  
Even [!= 1](https://steamdb.info/search/?a=app_keynames&type=1&keyname=375&operator=4&keyvalue=1) doesn't work :(

**Comment by xPaw** [comment]
There is no way to find keys that are not set as they are not in the table. Finding these would require a completely different query.

**Comment by gh89275** [comment]
Could you write one? Expose that functionality on the steamdb website? It'd be quite useful!

**Comment by xPaw** [comment]
I'm not sure it is useful. It would find all the apps that aren't public, and as such have no keys visible.

**Comment by gh89275** [comment]
Perhaps `community_hub_visible` was a bad motivating example. I think there are many other keys that are sometimes absent, even though the app is published and available.
