### ISSUE TITLE
Feature: Last Depots Update (option to remove?)

### ISSUE THREAD

**Issue by funnelfactory** [SteamDatabase/steamdb.info#488]
With the newest update in Firefox (1.7.2), there is a line with "Last Depots Update" and a date with how many days ago below the game's release date. Is there an option to remove this? Also, why is this information there/important?

Thanks.

**Comment by Marlamin** [comment]
https://steamdb.info/forum/1526/last-depots-update-on-store-pages/

**Comment by funnelfactory** [comment]
Thanks Marlamin but I think there should be an option that is directly connected to "Last Depots Update". Right now if I disable "Add a block on Steam Store displaying online stats" in options this also turns off player counts, which I do not want to do. So there should be more specific options regarding the two very diferent displays of information.

**Comment by Marlamin** [comment]
We'll take it under consideration, but going off the last update we shipped it might be a while before it goes live.

**Comment by Korb** [comment]
> https://steamdb.info/forum/1526/last-depots-update-on-store-pages/

> Got an HTTP 302 response at crawl time
> Redirecting to https://steamdb.info/discord/
