### ISSUE TITLE
Showing wrong SteamID

### ISSUE THREAD

**Issue by MaliceUnarmed** [SteamDatabase/steamdb.info#490]
The SteamID is displayed incorrectly on my page:
https://steamdb.info/calculator/76561197960394475/?cc=us
It shows:
SteamID: STEAM_1:1:64373

My actual ID is:
SteamID: STEAM_0:1:64373

It's suppose to be a 0 not a 1 at the beginning, the other SteamID is actually an ex TFC clanmate of mine from 15 years ago lol. If I enter my SteamID or his in to the website they both go to my page as well but would be nice if it displayed my actual SteamID.

Thanks.

**Comment by rossengeorgiev** [comment]
The correct SteamID is STEAM_1:1:64373

The 0 in the other is a result of bug in the old source engine. Both represent the same SteamID in the end. The calculator working correctly.
