### ISSUE TITLE
Add SHA1 Checksums To VPK File List Instead of CRC

### ISSUE THREAD

**Issue by Alamer99** [SteamDatabase/steamdb.info#491]
Hello,

Can you please use SHA1 checksum for [VPK Archives File Lists](https://github.com/SteamDatabase/GameTracking-CSGO/blob/master/csgo/pak01_dir.txt)

Right now it uses this format
[Path\Inside\Archive] CRC:[CRC Checksum] size:[File Size]

Could you change the CRC to SHA1? or maybe add SHA1 to it?

**Comment by Netshroud** [comment]
The `_dir` VPK contains within it the CRC of the file content, which is what is shown here.

To calculate another checksum for a file, one would have to independently re-hash the file data.
