### ISSUE TITLE
Planetary Annihilation: TITANS

### ISSUE THREAD

**Issue by Kharnellius** [SteamDatabase/steamdb.info#492]
The pricing for Planetary Annihilation: TITANS is pointing towards the price for the **Upgrade** from regular "Planetary Annihilation" to "Planetary Annihilation: TITANS".

> Buy Planetary Annihilation - Upgrade to Titans
> Buy this if you own Planetary Annihilation on Steam for a special upgrade price.

> $13.59  
> Add to Cart

https://steamdb.info/app/386070/info/

Strangely enough, the actual upgrade has it's own page, but no information.
https://steamdb.info/app/420120/subs/

Even the bottom of the above page links to the correct price of $39.99 even though the price history shows it is currently $13.59.

I'm wondering if this is a common issue for add-ons, upgrades, etc.

Images:
![steam](https://cloud.githubusercontent.com/assets/27926254/25316268/7bfe5e9c-2829-11e7-84fe-f6a39e7f3c5b.PNG)
![steamdb](https://cloud.githubusercontent.com/assets/27926254/25316267/7bfdf632-2829-11e7-970b-5591fe8f5312.PNG)

**Comment by xPaw** [comment]
#463

**Comment by xPaw** [comment]
This is fixed now.
