### ISSUE TITLE
Steam App ids changed

### ISSUE THREAD

**Issue by drats666** [SteamDatabase/steamdb.info#493]
grand theft auto 3 is now id 12100 calculator list it as 12230
so anyone with the game it shows up at no price.
grand theft auto san andreas is now 12120
Company of Heroes is now 4560
Grand Theft Auto: Vice City is now 12110
Sid Meier's Civilization IV  is now 3900

**Comment by xPaw** [comment]
There are different versions (e.g. regional copies).
