### ISSUE TITLE
Wrong CIS flag

### ISSUE THREAD

**Issue by alexmiron** [SteamDatabase/steamdb.info#496]
The correct CIS confederation flag is [this one](https://en.wikipedia.org/wiki/Flag_of_the_Commonwealth_of_Independent_States).
![sketch](https://user-images.githubusercontent.com/23292385/27244284-8cb387e0-52ee-11e7-8089-f5f519e09f29.png)

**Comment by xPaw** [comment]
This is deliberate as it shows flag of the country that we use to fetch prices. If a game is available in some CIS country but not the one we use to fetch, that CIS price will be missing.
