### ISSUE TITLE
"not logged in on Steam Store" - but I am

### ISSUE THREAD

**Issue by username35** [SteamDatabase/steamdb.info#499]
I constantly get the message "You are not logged in on Steam Store, owned game highlighting won't work."

It's right about the owned game highlighting not working, the "Hide owned games" option is clickable but has no effect, while the "Show wishlisted only" option (my main reason for signing up) is unclickable.

However, I am logged in with the same Steam account on both steamdb.info and store.steampowered.com (I see my avatar in the top right corner on both pages). I use Firefox 54.0 and have the Steam Database addon installed.

**Comment by xPaw** [comment]
Perhaps you are blocking third-party cookies?

**Comment by username35** [comment]
Yes, that was it. It took some trial and error, but setting steampowered.com (not store.steampowered.com) as an exception in FF's third-party cookie options did the trick.
Thank you!
