### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by Nucleoprotein** [SteamDatabase/steamdb.info#501]
I get a error when I'm redirected from Steam OAuth page to steamdb:

"There’s an issue with the database.
Code 42000. Please try again later."

Tested on Firefox and Chrome, I will test on different PC tomorrow.

**Comment by xPaw** [comment]
Should be fixed now, thanks!

**Comment by Nucleoprotein** [comment]
That was fast, thanks !

**Comment by JStephens33** [comment]
I've got:

 "This challenge page was accidentally cached and is no longer available.

If you are having issues, make sure that you are using a fully up to date browser.

RAY: 6d8f43125efb82ea"

What does this mean?

**Comment by JStephens33** [comment]
It's all good, I just logged in on my old laptop
