### ISSUE TITLE
Dark Souls II SotFS "incorrect" price

### ISSUE THREAD

**Issue by Psycheage** [SteamDatabase/steamdb.info#502]
SteamDB lists Dark Souls II SotFS as being $29.99 when that is really just the upgrade price while the "real" price is $39.99. I assume this has happened because the automatic process takes the lowest current price on the store and uses that. I don't know if this is that big of a deal to you but I just wanna let people know.

**Comment by xPaw** [comment]
Duplicate of #463.

**Comment by xPaw** [comment]
This is fixed now.
