### ISSUE TITLE
Sorting disappears after refreshing sales page

### ISSUE THREAD

**Issue by Yellow-Horror** [SteamDatabase/steamdb.info#503]
Every time the sales page is reloaded in browser, current titles sorting is lost despite sorting symbol reappears in the right place and form.

**Comment by xPaw** [comment]
Huh, could you elaborate?

**Comment by Yellow-Horror** [comment]
It seems that titles are sorted by score by default, and this sorting returns after the page refreshing. And i was wrong about the sorting symbol behavior. Anytime after the page refreshing, three columns are marked as sorted in descending order: name, discount percentage and score (which is not true for the first two).

**Comment by xPaw** [comment]
It won't keep your sorting after you refresh the page, that's expected.

It sorts by: category (where daily deal is at the very top), reviews and then the discount percentage.

**Comment by Yellow-Horror** [comment]
Ok, i uderstand. But it may be much better if i can store my own sorting criteria somehow. So, consider that i request such a feature for future development.
