### ISSUE TITLE
DLCs not listed in unfiltered view

### ISSUE THREAD

**Issue by username35** [SteamDatabase/steamdb.info#504]
There are filters like "Games only" and "DLCs only" which work fine on their own. However, when I don't have any filter selected and check "Show wishlisted only" only the games on my wishlist are shown, but not the DLCs. The only way to see my wishlisted DLCs on SteamDB is to set the filter "DLCs only", but then I won't see any games any more. I would like to see everything that's on my wishlist in one view.

**Comment by xPaw** [comment]
This is expected, there are so many DLCs that we opted into filtering them out of the main view. You can use "DLCs only" and "DLCs for owned games" for that.

**Comment by username35** [comment]
Yes, I can understand that, but what about a "show all wishlisted items" option?

**Comment by xPaw** [comment]
This is tricky as the server does not know what you have in your wishlist.

**Comment by username35** [comment]
Strange. How does "Show wishlisted only" even work, then?

**Comment by xPaw** [comment]
SteamDB extension implements that.

**Comment by username35** [comment]
Ah, ok. Something tells me that it should be possible to implement the "show all wishlisted items" as well then, but I guess you as the developer know better whether it's worth the effort. Thanks for answering, anyway.
