### ISSUE TITLE
Price/hour sorting

### ISSUE THREAD

**Issue by Infirmarian** [SteamDatabase/steamdb.info#507]
The sort titles in the steam calculator is not functioning correctly, returning an unsorted list of games, rather than sorting by price/hour. Other sorts on the list of games owned seem to function, such as sort by time spent, as well as sort by rating and price.

**Comment by xPaw** [comment]
It works fine. It just has to put games without prices/hour calculated at the bottom, and the ones with price/hour calculated come after at. If you skip to last page (or sort in descending order) you will see that it is sorted.
