### ISSUE TITLE
Calculator roulette only displaying games from first page of owned products

### ISSUE THREAD

**Issue by Californ1a** [SteamDatabase/steamdb.info#508]
![](http://i.imgur.com/uZJqQAz.png)
By default, the Products tab shows 10 games per page now.

The roulette on the Information tab only goes through those couple games (by hitting "I don't want to play this"). No matter how I manipulate the listing on the Products page, the roulette still only goes through those couple games instead of my whole library.

I like the idea of being able to filter which games are included in the roulette, though, if that is where this leads. However, I'd much rather roulette my whole library until then instead of only my top 10 most played games.

**Comment by xPaw** [comment]
Fixed.
