### ISSUE TITLE
money convert....

### ISSUE THREAD

**Issue by ccsimplyspolit** [SteamDatabase/steamdb.info#509]
US DOLLAR
![US DOLLAR](https://image.prntscr.com/image/TNtpKpfZR__y11SG7y8CMA.png)
RUSSIAN RUBLE
![RUSSIAN RUBLE](https://image.prntscr.com/image/9xZr3zh_ThusmMKH4fEIlA.png)

Google Convert US Dollar to Russian Ruble
![Convert](https://image.prntscr.com/image/jZYHhmVuQImSENKcP-iZAQ.png)

Another Calc
US DOLLAR
![US DOLLAR](https://image.prntscr.com/image/lfMeJlQPS7SV1ScCLiDdSw.png)
RUSSIAN RUBLE
![RUSSIAN RUBLE](https://image.prntscr.com/image/4e69YR0xRBmKAzimZdWgGA.png)

Google Convert US Dollar to Russian Ruble
![Convert](https://image.prntscr.com/image/-YglgUVzQ3_b6-q4Rh20Xg.png)

**Comment by xPaw** [comment]
We use Russian prices from Steam Store, not converting them from USD in calculator.

**Comment by ccsimplyspolit** [comment]
Do wanna say, that if bought games on Russia Region, they will be cost ~50$, and if i bought games on USA region, they will be cost 112$? yep?

**Comment by xPaw** [comment]
Yes.
