### ISSUE TITLE
Price/Hour Sort

### ISSUE THREAD

**Issue by H0lland** [SteamDatabase/steamdb.info#510]
Since the implementation of selecting a number of games to display instead of defaulting to all of them, I've noticed the Price/Hour sort feature hasn't been working for me.

**Comment by xPaw** [comment]
It's not broken, if you sort twice you can notice that price/hour sorts correctly in descending order.

**Comment by H0lland** [comment]
Still running across this: 
![steamdb](https://user-images.githubusercontent.com/15065960/28425377-1ac85ff6-6d3e-11e7-86c8-1e304fd031f7.png)

Also I just wanted to say, thanks for your timely response earlier.

**Comment by xPaw** [comment]
So that's why I didn't see the issue, it only happens on certain profiles. Has to be a datatables issue.

**Comment by trapbuilder2** [comment]
Whenever I sort by price/hour, it seems to just put the games in a random order with unpayed games either at the top or bottom.

**Comment by trapbuilder2** [comment]
This instance has the first lot in order and hen just starts throwing them in randomly.
http://imgur.com/t8k2mx9

**Comment by xPaw** [comment]
@trapbuilder2 This is basically a datatables issue, and I am not sure to fix it, as I set `data-sort` on every column/row.

**Comment by xPaw** [comment]
Actually nevermind, I just fixed the issue.
