### ISSUE TITLE
New graphs - is useless(

### ISSUE THREAD

**Issue by PinoklGames** [SteamDatabase/steamdb.info#511]
http://prntscr.com/fy4g7x

sorry, but it sucks...
When I looked on it before, I saw the difference between the games. Which one is making good tail after discounts and which is not.

It was information about quality on game start, how fast it drops down,
And it was one of the most important metrics for me.  :(

**Comment by xPaw** [comment]
This was not intentional as we lost some data. We will try restoring it this or next week.

**Comment by PinoklGames** [comment]
Hi! Thanks a lot for a quick response. Ok, I thought that was some kind of optimization.

Отправлено с iPhone
