### ISSUE TITLE
API or downloadable database for package names

### ISSUE THREAD

**Issue by PowerGamer1** [SteamDatabase/steamdb.info#512]
Does SteamDB still able to acquire Steam package names as described here https://steamdb.info/forum/705/how-to-get-real-package-names/ ? If yes, it would be nice to have either API or downloadable database just for package names on SteamDB. In second case such database file can be in xml, json, KeyValues or other format and contain only package ID and corresponding package name for all Steam packages for which SteamDB has a name.

**Comment by xPaw** [comment]
No that method does not work. And we have no plans to provide dumps like this.

**Comment by PowerGamer1** [comment]
Are you saying package names on SteamDB are no longer automatically updated? If they are updated can you share your method of acquiring package names from Steam then?

**Comment by xPaw** [comment]
We only have names for packages that are visible in the store, and free on demand (from account page).
