### ISSUE TITLE
Wrong history prices for game Darkwood

### ISSUE THREAD

**Issue by k-gudulin-parcsis** [SteamDatabase/steamdb.info#516]
Game Darkwood was released in 17.07.2017 (as it appear at Steam page http://store.steampowered.com/app/274520/Darkwood/), but prices history for this game (https://steamdb.info/app/274520/) contains prices in 2016, 2015 and even 2014 years, when this game doesn't exist. It seems that something messed up

**Comment by xPaw** [comment]
It was in Early Access back in 2014. https://web.archive.org/web/20141210025413/http://store.steampowered.com/app/274520/
