### ISSUE TITLE
Update Package names

### ISSUE THREAD

**Issue by 872517414** [SteamDatabase/steamdb.info#520]
Steam Sub 133828
Counter-Strike: Global Offensive Perfect World
![2](https://user-images.githubusercontent.com/9050713/30963774-521628f6-a481-11e7-9012-609287ce1f25.png)

Steam Sub 211096
Counter-Strike: Global Offensive (Free CN)
![1](https://user-images.githubusercontent.com/9050713/30963778-55e62b52-a481-11e7-86dc-252db5f8c449.png)

**Comment by xPaw** [comment]
Don't change package names manually, thanks for the info though.
