### ISSUE TITLE
Quick consecutive clicks of "It works" on linux hints fail to create a commit

### ISSUE THREAD

**Issue by oprypin** [SteamDatabase/steamdb.info#521]
Go to https://steamdb.info/linux/hints/ (with auto-commit access), click "It works" on two games in quick succession. Only the first of them gets the corresponding commit created. It is also subsequently impossible to get an automatic commit created for the latter, because it just says "Already voted".

I just had this happen for "SWARMRIDER OMEGA (714240)" (succeeded) and "TTV2 (701470)" (silently failed). Also apparently "Red Game Without A Great Name (701470)" silently failed for me earlier.

**Comment by xPaw** [comment]
I added some locking to hopefully mitigate this problem.
