### ISSUE TITLE
Extension feature request: Show Steamdb rating in the Steam wishlist page

### ISSUE THREAD

**Issue by funnelfactory** [SteamDatabase/steamdb.info#522]
First, thank you for adding the new Steamdb rating score to the extension. This really helps.

In addition to that, I would like to put a request for the new Steamdb rating to also appear in the Steam wishlist page through the extension. I believe this would help to get an idea of how well received a game has been when looking at one's Steam wishlist during sales. This would give the user an overall view of the Steamdb rating score in conjunction with the sale price, which go together anyway. This would also allow users to reorganize their Steam wishlists based on the new Steamdb rating score, which is very helpful when going through very long Steam wishlists.

Thank you and keep up the good work.

**Comment by xPaw** [comment]
Extension has a separate repository: https://github.com/SteamDatabase/BrowserExtension/issues

But implementing this would take some effort, because wishlist page itself does not have any rating data on it, and it would require doing an API call for each game to display it.
