### ISSUE TITLE
Test browser notification on Realtime Stream

### ISSUE THREAD

**Issue by MikeLund** [SteamDatabase/steamdb.info#526]
It would be useful to have a button to trigger a test notification on https://steamdb.info/realtime/, ideally with a few seconds delay after clicking it. 

I wanted to see how these notifications work on my phone, but I see no way of doing this -- other than of course waiting for some Watched app update, and praying that a notification will actually work on my device.

**Comment by xPaw** [comment]
Notifications definitely won't work on mobile phone due to browser limitations.

**Comment by xPaw** [comment]
I have added a button to test notifications and extra checks.

**Comment by MikeLund** [comment]
Woah, you're fast, thanks a lot!

And so bigger changes making it into a ServiceWorker notification would be needed then for mobile support ([this demo](https://gauntface.github.io/simple-push-demo/) for example works on mobile)? Hope that can happen in future, for mobile notifications, but thanks again for the test button :)

**Comment by xPaw** [comment]
I have added serviceworker notifications. Do keep in mind that the websocket has to be alive for update to come through and notification to appear. Mobile devices can kill background pages.
