### ISSUE TITLE
our graphs is spoiled by twitch numbers

### ISSUE THREAD

**Issue by PinoklGames** [SteamDatabase/steamdb.info#527]
Hi guys! I love your servise, thanks for the great job you do!

Here some case wich is not quite usefull:
http://prntscr.com/h03tzi

Twitch numbers are so much biger then CCU of our game, that we actualy can't see them..:(
It would be great to have checkbox to disable twitch on graph just to watch other numbers included.

**Comment by Marlamin** [comment]
Which game is this?

**Comment by PinoklGames** [comment]
Party Hard tycoon

**Comment by Marlamin** [comment]
xPaw just enabled the legend on player graphs, so you can now toggle display by clicking on "Twitch viewers".

**Comment by PinoklGames** [comment]
It is awesome!! Thanks!
