### ISSUE TITLE
Charts date offset/shift feature to align by release date

### ISSUE THREAD

**Issue by Kein** [SteamDatabase/steamdb.info#529]
1. Ability to compare SteamSpy owners values in graph view between 2+ products
2. Ability to add a date shift/offset in comparison mode to a specific product to align comparison graph  for more readable/usable view. For example, if Product1 was released on Jan 1 2017 and Product2 was released on Oct 1 2017 I want to shift the graph for Product1 by +9 months.

**Comment by xPaw** [comment]
Done.

**Comment by Kein** [comment]
The aligment works, but not in a way I was expecting or describing it, I might have failed to be more precise.

Right now, if I compare, for example, 2 games, it aligns to the most recent release and then just cuts any data before that from the oldest release and then renders comparison graph. But the idea I had is to align in to one common date as a release point and then compare. For example, take Subnautica games:
https://steamdb.info/graph/?compare=848450, 264710&release

What I expected from alignment is to set same released date for both items and then overlay the charts in comparison - this way I can easily and at-a-glance compare how both games did in the first few X (hours/days/week/years) of the release.

`Obviously I could do it in any image-splicing tool/Photoshop but the point was to have the ability to do it in-place, quickly.`
