### ISSUE TITLE
Trying to calculate my Steam account worth. But it doesn't register my updated privacy settings.

### ISSUE THREAD

**Issue by IGoDoubleHat** [SteamDatabase/steamdb.info#535]
![help](https://user-images.githubusercontent.com/34003051/33240527-588a181e-d2b7-11e7-83d6-ddcb5e285b08.png)
I have synced my account several times. (1minute before taking the screencap)
I have reupdated my privacy settings to public.
Still doesn't work.
Help.

**Comment by xPaw** [comment]
Data is cached for an hour.
