### ISSUE TITLE
[GameTracking] Please consider not running the strings through c++filt. Or at least tune it better. It makes a mess of non-symbolic strings right now.

### ISSUE THREAD

**Issue by sigsegv-mvm** [SteamDatabase/steamdb.info#537]
I've grown tired of seeing regular strings getting interpreted as if they're C++ mangled symbols and "demangled" into nonsense, over and over and over.

Example. Actual string:
```
Bookkeeping bug: Can't remove logical socket from physical socket's table, it isn't there
```
[Shows up as this in the strings dump](https://github.com/SteamDatabase/GameTracking-TF2/commit/9943a58b04469cf1aaaefbad470f610891a89fea#diff-b837e37047ea5b536c0bf8e2d41a26d7R1834):
```
Bookkeeping bug: Can'unsigned short remove logical socket from physical socket'short table, it isn'unsigned short there
```
This happens *all the time* and it tends to make the string dumps a pain to read through.

----

[The script for doing the dumps](https://github.com/SteamDatabase/GameTracking/blob/master/common.sh#L34) currently invokes `c++filt` with `-t` and `-_`.

The `-_` is justified, since Clang on macOS prepends an extra underscore to mangled names.

But `-t` is questionable. To quote [the man page](https://linux.die.net/man/1/c++filt):
> Attempt to demangle types as well as function names. This is disabled by default since mangled types are normally only used internally in the compiler, and they can be confused with non-mangled names. For example, a function called "a" treated as a mangled type name would be demangled to "signed char".

So even the man page is like "you probably don't want to use this, because it can result in getting confused and demangling things that were not mangled in the first place".

So probably get rid of `-t`, unless there's really truly a good reason to keep it there.

----

And frankly, I'd even say that running the string dumps through `c++filt` *at all* is superfluous. Isn't that what *the symbol dumps* are for...? Would it really be so bad if the symbol names that happen to also sneak into the string dumps aren't demangled there, if it means that non-symbol strings are saved from getting screwed up in the string dumps?

Or are there sometimes symbols that *only* show up in the string dumps for some reason, or something? I'm somewhat curious as to why the whole running-string-dumps-through-`c++filt` thing was started to begin with.

Thanks.

**Comment by xPaw** [comment]
I agree that string dumps are less than ideal and this doesn't help, I haven't found a better solution for this. I will remove that flag though.
