### ISSUE TITLE
Linux titles by Linux release date?

### ISSUE THREAD

**Issue by eikesauer** [SteamDatabase/steamdb.info#538]
Humble feature request

We Linux gamers struggle with a problem since Steam for Linux was released: Often, games come later for Linux than for Windows, and Steam doesn't offer us a way to find games which are newly ported to our system. Is there, or could there be, a thing like a Linux release date in the SteamDB? Would it be possible to get a table of games for Linux, sorted by this date?

**Comment by xPaw** [comment]
https://steamdb.info/linux/ Date here is when the game is confirmed. That page relies on manual confirmations from Linux users (https://github.com/SteamDatabase/SteamLinux), as there is no reliable way of telling when a game will actually work on Linux.
