### ISSUE TITLE
[Request] Discord Server

### ISSUE THREAD

**Issue by PointyDev** [SteamDatabase/steamdb.info#539]
Hey there SteamDB peeps,

Noticed you peeps have an IRC channel on freenode, and I was thinking it'd be cool if you had a [Discord](https://discordapp.com/features) server. This would be pretty cool alongside/instead of the IRC!

Thanks,
Pointy

**Comment by xPaw** [comment]
No thanks.

**Comment by rossengeorgiev** [comment]
Oh how the tables have turned
