### ISSUE TITLE
Calculator SteamDB can't work

### ISSUE THREAD

**Issue by LockerTV** [SteamDatabase/steamdb.info#542]
My Steam profile and more steams account can't view by SteamDB Calculator
https://steamdb.info/calculator/76561198278976653/?cc=il
this is my link ID on SteamDB
and below my Profile
http://steamcommunity.com/id/MyShadows
![image](https://user-images.githubusercontent.com/34686521/34165546-3f361940-e4e5-11e7-96fc-4e7a418eeb9d.png)

**Comment by xPaw** [comment]
Steam API may have hiccups, it's working fine atm.

**Comment by LockerTV** [comment]
Well, it's will fix soon?

**Comment by xPaw** [comment]
Your own link is working fine.

**Comment by LockerTV** [comment]
the SteamDB can't view my account on my country currency..
Israel new Shekels

**Comment by xPaw** [comment]
It's working fine.

![19-155690529](https://user-images.githubusercontent.com/613331/34165818-f8ada94c-e4e5-11e7-8f5b-3cf29fbcf4e1.png)

**Comment by LockerTV** [comment]
for me not XD thanks :)
I'll see iot soon
