### ISSUE TITLE
Calculator XP progress-bar is overfilled

### ISSUE THREAD

**Issue by ErikHumphrey** [SteamDatabase/steamdb.info#543]
CSS says it's showing 98% when it should be 22%.

![Badges](https://i.imgur.com/1egkevg.png)
![Calculator](https://user-images.githubusercontent.com/1473776/34279289-0bbae506-e67e-11e7-8482-4a2ca480d634.png)

**Comment by metonator** [comment]
Looks correct for me, (67467/68400)*100 is in fact ~98.64%, while steam simply calculates its percentage every few steps, in your case: 

```
(110*10)+100=1200 [steam counts xp leveling every 10th lvl, in your case, 110 instead of 111]
1200-933=267
(267/1200)*100=22.25%
```

Hope you understans my bad math

**Comment by xPaw** [comment]
Yeah, it calculates the bar for each level.

**Comment by ErikHumphrey** [comment]
Why would anyone want it to be displayed this way, though? While harder to implement, shouldn't the progress bar represent the XP from level 111 to level 112 (1200 XP) rather than current total XP out of total XP for next level? While it says 933 XP needed, the bar is almost useless and is hardly representative of any sort of progress; the blue will only fill up slightly more with each level until the grey area is infinitesimally small.

**Comment by xPaw** [comment]
If you can give me a formula to calculate XP until next %10 level, I can switch it out.

**Comment by metonator** [comment]
Well, here you go:

```php
<?php

  $steamid = "76561198026886659";

  $steamapi = json_decode(file_get_contents("https://api.steampowered.com/IPlayerService/GetBadges/v1/?key=<<<STEAMDEVAPIKEY>>>&format=json&steamid=".$steamid), true);
  $player_level = $steamapi['response']['player_level'];
  $player_xp_needed_to_level_up = $steamapi['response']['player_xp_needed_to_level_up'];

  $xp_by_level = ($player_level-($player_level%10)+10)*10;
  $total_xp_for_actual_level = $xp_by_level-$player_xp_needed_to_level_up;
  $real_percentage = ($total_xp_for_actual_level/$xp_by_level)*100;

  if($real_percentage <= 10) {
    $percentage = 10;
  } else {
    $percentage = floor($real_percentage);
  }

  echo $percentage;

?>
```

Tested with 5 profiles, it returns its width correctly

**Comment by xPaw** [comment]
Thanks! I switched it out on the site.
