### ISSUE TITLE
Filter items using regional prices difference

### ISSUE THREAD

**Issue by olloff** [SteamDatabase/steamdb.info#552]
Hi.

Is it possible to filter games with huge price difference within selected regions? 
Here are examples of price advantage in one country to another - https://imgur.com/a/fGl2P - and its hard to estimate how many products are subject of this problem. 

Use cases:
1. Due to Steam regional price restrictions, there is no way to send gifts to users from region with price difference more than 10%. 
2. Some developers/publishers won't set regional prices in some regions leading to huge price disadvantage (e.g. australian prices).

**Comment by xPaw** [comment]
We have https://steamdb.info/priceglitches/ for that, but that's about it.
