### ISSUE TITLE
Profile is private unable to pull data

### ISSUE THREAD

**Issue by tht1neet** [SteamDatabase/steamdb.info#554]
My steam profile has never been private so i don't understand why it keeps saying this in regards to pulling up my steam info. This site worked last time i tried it last year so i'm confused as to why i'm encountering this issue since i haven't changed my settings.

**Comment by xPaw** [comment]
If it says the profile is private, then it is. That's what the Steam API says.

**Comment by tht1neet** [comment]
The thing is I've never had my profile private so I don't understand why it says my profile is private?

**Comment by xPaw** [comment]
URL?

**Comment by tht1neet** [comment]
I've never changed my settings on there

http://steamcommunity.com/id/that1neet

**Comment by xPaw** [comment]
Come on.

![07-081490893](https://user-images.githubusercontent.com/613331/35905413-b489e768-0bef-11e8-96e4-dd0f2a8f35d7.png)

**Comment by tht1neet** [comment]
Hmm why did it work last year though if my settings haven't been changed o:
