### ISSUE TITLE
can you give API for developers?

### ISSUE THREAD

**Issue by LordVersA** [SteamDatabase/steamdb.info#555]
can you give API for developers to use it in their website or applications, it can be very usefull

**Comment by xPaw** [comment]
No intentions.

**Comment by zepumph** [comment]
I would definitely use an API if there was one.  Have you by chance changed your mind? :)

**Comment by xPaw** [comment]
https://steamdb.info/faq/#does-steamdb-have-an-api

https://steamdb.info/faq/#can-i-use-auto-refreshing-plugins-or-automatically-scrape-crawl-steamdb
