### ISSUE TITLE
Error in label - Fallout 4

### ISSUE THREAD

**Issue by Galanthys** [SteamDatabase/steamdb.info#556]
Hello there,
Fallout 4 free week ended the 4th of this month (6 days ago), but it still appears as Free to Play ever since.

![db wrong label](https://user-images.githubusercontent.com/36333309/36062868-15c0125a-0e75-11e8-96f2-bd9e1a58456a.png)

Have a nice day !

**Comment by xPaw** [comment]
Fixed, caches still need to expire though.
