### ISSUE TITLE
Incorrect price values

### ISSUE THREAD

**Issue by instinctbluez** [SteamDatabase/steamdb.info#561]
I don't quite understand how an item at 60% discount can cost both 719 & 199.
![firefox_screenshot_2018-02-17t00-22-00 226z](https://user-images.githubusercontent.com/24224188/36335555-e0ca2e00-13a6-11e8-8a20-26358576e0dc.png)
Also, I'm not sure about the lowest recorded price of the item. It couldn't have been 199 ever.

**Comment by xPaw** [comment]
It choses the lowest price, so if a bundle was cheaper the % can be different.
