### ISSUE TITLE
Life is Strange

### ISSUE THREAD

**Issue by tom526** [SteamDatabase/steamdb.info#562]
Life is Strange is a MacOS compatible game, but when I change the search to Mac only, it disappears from the list.

https://steamdb.info/sub/56692/

**Comment by xPaw** [comment]
Can you give an exact url to the search?

**Comment by tom526** [comment]
This link shows Life is Strange:  https://steamdb.info/sales/?min_discount=0&min_rating=95

This link, with Mac filter, does not:  https://steamdb.info/sales/?min_discount=0&min_rating=95&category=998

BTW, your site is awesome!  I'm on it everyday, and has saved me a ton of money!!
________________________________

**Comment by xPaw** [comment]
If you mean sales filtering, then that's expected. Packages don't have an OS defined, apps do, and unfortunately we can't filter packages like that.

**Comment by tom526** [comment]
Makes sense.
Thanks for the quick reply!
________________________________
