### ISSUE TITLE
[Suggestion] Stuff to /stats/ + More stuff

### ISSUE THREAD

**Issue by FuryEthan** [SteamDatabase/steamdb.info#563]
Hey so i think it would be cool if you could add a few things.
They don't require much code and i'm sure they're reasonable suggestions.

When hovering over 'stats', you're able to see "Top Game Owners", "Top Steam Levels" and so forth.
I think there should be more added.
Such as, Top hours, Top Average Play Time, Top Account Value, etc.

I also think more should be added to the calculator.
Example: https://imgur.com/gallery/gkJuN
Such as Screenshots, Videos, Workshop Items, etc.
Then add them to the stats list too.
Such as, "Top Videos", "Top Screenshots", etc

Hope you take these ideas on board.
Sorry if this was posted in the wrong place, wasn't sure where to post it.

**Comment by xPaw** [comment]
> Top hours

Possibly.

> Top Average Play Time, Top Account Value, etc.

We don't store the data to calculate these, and have no plans to.

> Such as Screenshots, Videos, Workshop Items, etc.
Then add them to the stats list too.
Such as, "Top Videos", "Top Screenshots", etc

These are only retrievable by parsing the community page and have very limited value, so we're not going to add these.
