### ISSUE TITLE
Few Issues: HTTPS, Forum, Spam.

### ISSUE THREAD

**Issue by Black3ird** [SteamDatabase/steamdb.info#567]
Hello,

Currently the SteamDB is putting Steam Store page links in **HTTPS** form such as from https://steamdb.info/app/826620/ as in **https**://store.steampowered.com/app/826620/?utm_source=...... . I didn't even notice this until Chrome gave an error because we all know Steam is **not using** HTTPS other than *needed* pages and such *incorrect* redirections can cause trouble as in my case. So please do not rely on Steam to *"correct"* (rare cases it doesn't) HTTPS to HTTP conversion and provide all Steam Store Pages link in HTTP instead.

As I was planning to ask this on https://steamdb.info/forum/ I also noticed there's **no way** to initiate a post by any means or any page I visit. There's only option to reply *existing* threads but that's all. If some reason this is an intended action, a top-most warning in every forum subsection would be nice. Tried on different accounts with vanilla browsers resulting same outcome.

Also while SteamDB exists in multi-platforms such as https://github.com/SteamDatabase/, https://steamdb.info/forum/ and https://steamcommunity.com/groups/steamdb, users are somewhat torn between where to post their thoughts. As part of that it's annoying to see a user using https://steamdb.info/forum/ to post her "Steam Top Sellers" posts which is utterly unnecessary for a forum that was supposed to discuss **only** SteamDB related topics, not Steam only ones. If she very much likes to do so, she could easily find a Steam or Reddit group to do her announcements which is already covered by other sites already.

None of them are big but thought these also need to be heard. Thanks for your time and efforts.

**Comment by DarkMio** [comment]
About HTTPS: Tell Valvo to fix their shit instead of SteamDB to route people to bad urls.  
About Forum: Well, you just now used a github issue to share your thoughts and prayers instead of the forum. Case closed on that one, Mulder.

**Comment by xPaw** [comment]
> as in https://store.steampowered.com/app/826620/?utm_source=...... . I didn't even notice this until Chrome gave an error because we all know Steam is not using HTTPS other than needed pages and such incorrect redirections can cause trouble as in my case.

We will not be changing URLs back to http for Steam domains.

>  There's only option to reply existing threads but that's all. If some reason this is an intended action, a top-most warning in every forum subsection would be nice.

Intentional. I'll look into adding a warning.

>  If she very much likes to do so, she could easily find a Steam or Reddit group to do her announcements which is already covered by other sites already.

Wendy is our bot that posts automatically.
