### ISSUE TITLE
"Hours on record" doesn't work

### ISSUE THREAD

**Issue by AWGEnough** [SteamDatabase/steamdb.info#568]
Gameplay hours recording looks broken, shows 0 for all games:

![cattura](https://user-images.githubusercontent.com/22817863/38299474-7b5f9adc-37fa-11e8-9eac-383ce58926fa.JPG)

**Comment by xPaw** [comment]
We calculate from what Steam API returns. I just checked a couple of profiles and they're fine.

Next time you report an issue include profile link which you see the issue for.
