### ISSUE TITLE
N/A replaced the price history if a game is giving out for Free (ie ckii) only for a limited time

### ISSUE THREAD

**Issue by JeffSoraRiku** [SteamDatabase/steamdb.info#571]
Crusader Kings II (203770) is giving free PERMANENT copies if you "buy" it within 48hrs. However, the "Current Price" as well as the "Converted Price" show NA instead of $0, in the corresponding page for the app. The price history correctly added a dot on 0.00, but instead of Discount: 100% the tooltips reads "No Discount" instead. I wonder if this was intended or just a little oversight as games aren't giving out free copy only for a period of time (instead of only playable like during the weekend) very often in steam. Thank you.

**Comment by xPaw** [comment]
There's no difference between 0$ and N/A, so this isn't an issue.

**Comment by JeffSoraRiku** [comment]
How about the "Lowest Recorded Price" which shows last positive price and lowest price?

**Comment by xPaw** [comment]
Due to Steam not having any proper API to get prices, we can't change it to say free/0$ for games that are given out.
