### ISSUE TITLE
steam profile worth not showing

### ISSUE THREAD

**Issue by warpigy** [SteamDatabase/steamdb.info#574]
says my profile is private but i know its not , and i set it to public, why wont this feature work anymore

**Comment by xPaw** [comment]
![11-155163007](https://user-images.githubusercontent.com/613331/38628132-55525fd6-3db9-11e8-8638-390a68590634.png)

**Comment by warpigy** [comment]
http://prntscr.com/j3vvgx
http://prntscr.com/j3vvob
