### ISSUE TITLE
Error when setting Colombian Peso as currency filter.

### ISSUE THREAD

**Issue by Agr3ssiv3** [SteamDatabase/steamdb.info#576]
Any other currency works, but my country dont, this is the error is showing.

Error!
Looks like our request has timed out or has received an error. Steam could be down or under high load right now. Please try again later.

Ty.

**Comment by Agr3ssiv3** [comment]
https://steamdb.info/calculator/

**Comment by Agr3ssiv3** [comment]
when checking an account value with colombian peso.

**Comment by xPaw** [comment]
Can't reproduce, the currency doesn't have anything to do with it either. Do as the message says: try again later.
