### ISSUE TITLE
A few users are still listed as having the Steamworks Developer badge when it has been removed.

### ISSUE THREAD

**Issue by Bonsai99** [SteamDatabase/steamdb.info#582]
Still shows up as them having the badge even after updating their profiles on SteamDB and it being gone from their Steam profile.

https://steamdb.info/badges/?badgeid=12

**Comment by xPaw** [comment]
It keeps popping up in the API even though I have cleared the day data before.

**Comment by xPaw** [comment]
This is an issue with Valve's API, it still reports that badge for some profiles.
