### ISSUE TITLE
RSS Incompatibility with IFTTT

### ISSUE THREAD

**Issue by nubpro** [SteamDatabase/steamdb.info#584]
The RSS feed (https://steamdb.info/api/PatchnotesRSS/?appid=570) does not work with IFTTT.
Whenever I try to add this RSS link, IFTTT will reply with a message "Feed is not reachable at this time". I tried accessing the link directly from my browser and it works just fine, so clearly the feed is accessible but maybe the format is not correct?

I dig this page out from IFTTT:
https://help.ifttt.com/hc/en-us/articles/115010396768-My-RSS-feed-is-not-working-correctly

I'm not sure whose fault is it directed at, but it will be great if you can make it work 👍

**Comment by xPaw** [comment]
Can't do anything about it with an descriptive error. Contact their support.
