### ISSUE TITLE
Anchor for badge IDs does not account for the sticky Rank/Level thead

### ISSUE THREAD

**Issue by Zarthus** [SteamDatabase/steamdb.info#585]
e.g. when you click on (which at this current point of time is on position 824) https://steamdb.info/badges/?badgeid=29#76561198011447878 it'll bring you to "half of 825", it does fix in on position 824, but on top of it is the thead overlay (xpath: `/html/body/div[1]/div[6]/table/thead`)

Visual Examples:
Clicking on ID "824" centers you on this position:
![steamdb_focus](https://user-images.githubusercontent.com/3660408/42053709-9202ba70-7b12-11e8-8355-8c1eec1311de.png)

You have to scroll up to see position 824:
![steamdb_scrollup](https://user-images.githubusercontent.com/3660408/42053707-916114c2-7b12-11e8-9acd-f3e76b38e132.png)

**Comment by xPaw** [comment]
Fixed.
