### ISSUE TITLE
Always show at least 2 digits for cents

### ISSUE THREAD

**Issue by MakoSipper** [SteamDatabase/steamdb.info#586]
![chrome_2018-07-31_22-47-47](https://user-images.githubusercontent.com/16372995/43496646-c9656226-9514-11e8-8c5c-755189261a02.png)
The price here should show as R$ 3,10
We always use the two digits for cents, even if the second one is zero. (The only exception is the price for fuel, which always use even three digits, but that doesn't really matter here.)

**Comment by xPaw** [comment]
Fixed, thanks
