### ISSUE TITLE
Please Move Away or Revert Back or Option to Disable recent Hover Game Information.

### ISSUE THREAD

**Issue by Black3ird** [SteamDatabase/steamdb.info#588]
Hello,

Today I woke up to a bad surprise of now SteamDB has introduced **un-navigable** game information Hover Boxes that _"disrupt"_ searching and finding games on https://steamdb.info/sales/ page. Before change it used to look like [this](https://imgur.com/POkG1mN) where if you click on longer game name it was opening SteamDB page and when you click on "small" Steam icon, it is opening Steam Store page instead. This still works for subs and alike that do **not** have Store pages for Hover Boxes.

But now it shows like [this](https://imgur.com/503MnaP) and you can **never reach** Steam Store Links because Hover Box as shown in image **blocks** all useful information such as said Store links, other games names etc. by its current placement. There is a _"vacant space"_ as shown [here](https://imgur.com/IYYSREa) where such Hover Box can be useful instead of _"hiding"_ other information such as list of games instead of one game occupying all space.

Noticed that Hover Box also includes Store Links at its bottom _but_ since it's _dynamically_ created, it breaks any userscript I've been using on SteamDB such as [this](https://greasyfork.org/en/scripts/26273-steam-web-integration/) which is quite useful. Same goes for the annoying previous update of Site Navigation Bar popping up **every** time when your mouse travels up and down regardless the fact that you don't intend to use Site Navigation Hover at all. In past, it used to hover over **only** required items now included every bit of space as a reason to show that hover to the point, I've **advert**-blocked it for good.

I know your intentions are good yet such improvements breaks the _"Fluidity"_ of SteamDB's usability and could be **optional** per user for the _other_ users also bothered with it but didn't voice their opinion here or elsewhere. If you want public opinion, I can bring same subject in Reddit forums pinging asd33 persona so that you'll decide what to do on user feedback.

If you're going to insist on keeping the same place instead of its **optimal** place shown in last image, please at least refer the script responsible for doing that hover so that I can ad-block it too for my convenience. 

Thanks for your time and patience to read my complaints.
Your work is much appreciated.

**Comment by xPaw** [comment]
I've moved the hover position on sales page.
