### ISSUE TITLE
Shank 2 doesn't list Linux in the "supported system" section

### ISSUE THREAD

**Issue by CuriousTommy** [SteamDatabase/steamdb.info#594]
I noticed that [Shank 2 (102840)](https://steamdb.info/app/102840/) listing does not show a tux icon. If you look at [the actual store page](https://store.steampowered.com/app/102840/Shank_2/?curator_clanid=4777282&utm_source=SteamDB), you will see the Steam OS icon there, indiciating that there is Linux support.

**Comment by xPaw** [comment]
It's up to developers to list it. Field in store is separate.

**Comment by CuriousTommy** [comment]
> Field in store is separate.

I am assuming that there is no way for SteamDB to access this info, right?

**Comment by xPaw** [comment]
Yes, we don't crawl OS info from the store.
