### ISSUE TITLE
Initialize Database

### ISSUE THREAD

**Issue by gd-narola** [SteamDatabase/steamdb.info#595]
We have api key for steam and one game in steam account. But when run this console application not getting any data. Do we need to add app manually in it?

**Comment by xPaw** [comment]
Full run it, the CLI tells you to do that.

**Comment by gd-narola** [comment]
Hello @xPaw 
Tried that as well set full run = 4 as per warning

**Comment by gd-narola** [comment]
It gets disconnected from steam and also it says some depot file is missing
