### ISSUE TITLE
Issue in publishing for linux due to NetIrc2 1.0.0

### ISSUE THREAD

**Issue by gd-narola** [SteamDatabase/steamdb.info#596]
When we restored package NetIrc2 got below warning:
Package 'NetIrc2 1.0.0' was restored using '.NETFramework, Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

project worked with that package and when tried to publish with this command:
 dotnet publish -c release -r ubuntu.16.10-x64

getting this error:
 error NU1605: Detected package downgrade: System.Diagnostics.Debug from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.

**Comment by gd-narola** [comment]
@xPaw  Would you please at least add some suggestion for this issue?

**Comment by xPaw** [comment]
It's just a warning, latest net core works fine with .net dependencies.
