### ISSUE TITLE
Please give option to filter so that results displayed are only blue and green discounts.

### ISSUE THREAD

**Issue by funnelfactory** [SteamDatabase/steamdb.info#599]
Please give option to filter so that results displayed are only blue and green discounts.

Right now there's a filter option to show only new discounts (blue) but there should also be a filter option to show listings "priced on par with lowest recorded price" (green). That way, we could look at the filtered results showing only blue and green results.

Thanks.

**Comment by funnelfactory** [comment]
xPaw, could you please mark this with as a "feature request" here? Also, when do you think this will be implemented on the site? I was hoping to already use this combination of filter features during the winter sale that just passed but this request has been opened for 1 and a half months already. Thanks again.

**Comment by xPaw** [comment]
I work on the site in my free time, so asking for a feature doesn't mean I will work on it straight away.
