### ISSUE TITLE
Wrong "Stats" button for games

### ISSUE THREAD

**Issue by sharkiller** [SteamDatabase/steamdb.info#605]
The link to achievements is broken on most games. 
Like [Assassin's Creed Odyssey](https://steamdb.info/app/812140/) the link for "Stats" button is https://steamcommunity.com/stats/812140/ but is missing the "/achievements" after the game id so steam redirect to a generic stat page.

Should be https://steamcommunity.com/stats/812140/achievements

**Comment by xPaw** [comment]
It will add `achievements` to the url now if schema with achievements is available.
