### ISSUE TITLE
Native linux games displayed as Windows-only

### ISSUE THREAD

**Issue by derpelikan** [SteamDatabase/steamdb.info#606]
Some games with native linux versions are shown as Windows-only in SteamDatabase.

Examples:
[8bit Fiesta](https://steamdb.info/app/382260/),
[Anodyne](https://steamdb.info/app/234900/),
[Shank2](https://steamdb.info/app/102840/)

Of those, only Shank2 is promoted as linux-compatible on the store page, but there may be others. 8bit Fiesta and Anodyne, while not promoted as linux compatible, have perfectly running linux versions and those are the default to run when installing them. Steams own linux filter will also recognize them as linux games.

**Comment by SinZ163** [comment]
with 8bit Fiesta, the `oslist` field does say its windows only, but it does have linux depots and a launch config specified for linux.

Similiar story with Anodyne, though the `oslist` specified windows and macos

**Comment by xPaw** [comment]
Ask developers of these games to fix it.

**Comment by derpelikan** [comment]
So, no discussion, no looking into the Shank2 case, no recommendation how to address the developers?
Thank you very much.

**Comment by xPaw** [comment]
There's nothing to discuss here, the OS list is controlled by the developers on the Steamworks website.

**Comment by derpelikan** [comment]
OK, I'll try. But to give you the reason I even stumbled upon this: I was redirected here by ProtonDB, because I found there to be compatibility reports on games that won't even use SteamPlay/Proton, because they run as native by default. There will always be "wrong" oslist entries for several games, but for a person running Steam on Linux and for the ProtonDB usecase, the fact, that there is a depot probably matters more then the oslist.
