### ISSUE TITLE
Add ProtonDB rating

### ISSUE THREAD

**Issue by Saphareas** [SteamDatabase/steamdb.info#607]
It would be very useful, if you would display the rating from protondb.com in a game's information.
Maybe it could look like this example for Monster Hunter: World
![bildschirmfoto vom 2019-02-18 16-42-45](https://user-images.githubusercontent.com/11543093/52962139-cab0a600-339c-11e9-8fa2-eff33f9435dd.png)

**Comment by xPaw** [comment]
I've heard reports on protondb can be questionable (e.g games marked platinum despite requering manual work).

I have no plans to add ProtonDB ratings on SteamDB.
