### ISSUE TITLE
Add ability to exclude certain tags (or other field qualifiers) in instant search

### ISSUE THREAD

**Issue by emmatoday** [SteamDatabase/steamdb.info#608]
It would be helpful to be able use exclude operators in search, like exclude certain tags, publishers, or features.

I'm not a UX person, but personally I kinda wish the buttons on the side would just dynamically update the search query above. So if I check the "adventure" tag while having searched for "cute", it would update the query to be:

```
cute tag:adventure
```

And if from there, I wanted to exclude a tag, maybe even use + and - buttons instead of check boxes. So if I click - on the "horror" tag it would update the query to be:

```
cute tag:adventure -tag:horror
```

You could also keep the little tag bubble buttons at the top for the field (non-full-text) matches, to keep it prettier and not go to a more CLI look. Maybe have green and red bubble buttons to show include vs exclude, and have a  + and - on them respectively to further indicate what they mean, or just a - on exclude to set it apart from the normal positive match. Then still only use the text box for the full-text search feature, but use the + and - on the sidebar instead of the check boxes, and have those update the tag bubble buttons on the top.

**Comment by xPaw** [comment]
You can exclude tags now.
