### ISSUE TITLE
The 7th Guest: 25th Anniversary Edition is Windows only

### ISSUE THREAD

**Issue by legluondunet** [SteamDatabase/steamdb.info#609]
Hello, the game The 7th Guest: 25th Anniversary Edition is Windows only. But on SteamDB:
https://steamdb.info/app/1044340/
it shows the three icons WIndows, Linux, Macosx for "Supported Systems".

**Comment by xPaw** [comment]
That's what developers marked it as, SteamDB simply shows that information.

**Comment by legluondunet** [comment]
For the developer, , it's a SteamDB bug, the game is marked as WIndows only on STeam, but his DLC is multiOS, so SteamDB report the game are multiOS too...
Please could you answer directly to the game's developer here:
https://steamcommunity.com/app/1044340/discussions/0/1815422173036189556/

**Comment by legluondunet** [comment]
Same bug for this games:
https://www.protondb.com/app/674150 (Windows only)
https://www.protondb.com/app/678760 (Windows only)

**Comment by legluondunet** [comment]
Since protonDB is sync with SteamDB, it shows this Windows only games  as Linux native:
https://www.protondb.com/app/1044340/
https://www.protondb.com/app/674150
https://www.protondb.com/app/678760

it's a real problem as it's impossible for Linux gamers to write a report for this games on ProntDB.

**Comment by legluondunet** [comment]
Please reopen this issue.

**Comment by legluondunet** [comment]
The dev updated his answer:
https://steamcommunity.com/app/1044340/discussions/0/1815422173036189556/
Could you discuss with him about this bug?
