### ISSUE TITLE
Long keys (4x7) not recognized when submitted

### ISSUE THREAD

**Issue by sparr** [SteamDatabase/steamdb.info#612]
I have a key of the form `XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX`, four groups of seven characters instead of the typical three groups of five. The key submission system regex doesn't seem to match this as a valid key and doesn't accept it.

**Comment by xPaw** [comment]
Where did you get that key from? I know other formats are possible and I specifically didn't code them in because they're rare.

**Comment by sparr** [comment]
Purchased a game bundle from Fanatical a few days ago, including the game "GT Legends" (Steam package(?) name "GT Legends Thirdparty Retail")
