### ISSUE TITLE
list of free packages not update

### ISSUE THREAD

**Issue by ashaserv** [SteamDatabase/steamdb.info#614]
Hello.

In script for adding free steam licenses on steam account list of free packages not update.
I see every day it now and now it not update, so i can not add new free licenses on my steam account.
extension error:
Failed to load game data from steam store (unfinded).

I ask developers steamdb, please make full list of all free packages on your site. From what list i can copy and paste in script 50 licenses and use script...

**Comment by xPaw** [comment]
> Failed to load game data from steam store (unfinded).

Login on the Steam Store and then do a force refresh.

**Comment by ashaserv** [comment]
I logged in steamstore!
I'm not first year use your script and know about login in steamaccount...

**Comment by xPaw** [comment]
Update extension to 2.1.2 and see which error message you get now (it should fix the `undefined`).

**Comment by ashaserv** [comment]
Where i can get new version?
Here i see https://chrome.google.com/webstore/detail/steam-database/kdbmhfkmnlmbkgbabkdealhhbfhlmmon 
2.1.1 and it already installed.

**Comment by xPaw** [comment]
Give it some time to update.

**Comment by ashaserv** [comment]
error:
Failed to load game data from Steam store. (Are you logged on the Steam Store?)
but i logged.

**Comment by xPaw** [comment]
Do you block third party cookies? Do you have other extensions that can interfere?

**Comment by ashaserv** [comment]
cookies not blocked.
I have 2 extensions: imacros and frigate but i disabled its because not need me now.
active only steam database

**Comment by xPaw** [comment]
I don't know, can't help you here.

I can only suggest to debug the extension yourself, if you know how to. https://developer.chrome.com/extensions/tut_debugging
