### ISSUE TITLE
RSS Feed for game updates

### ISSUE THREAD

**Issue by Bluscream** [SteamDatabase/steamdb.info#615]
It would be really neat if there was something like
- https://steamdb.info/app/438100/history/?format=rss

**Comment by xPaw** [comment]
Theres literally an RSS button on the patches page you linked.

**Comment by Bluscream** [comment]
I am not interested in the patchnotes they make ever 50th update (Compare [this](https://steamdb.info/patchnotes/?appid=438100) to [that](https://docs.vrchat.com/docs/vrchat-201921p2)) I want myself and my users to be updated everytime there is a change to the master branch that would trigger a update in steam.
