### ISSUE TITLE
Lost the game from the SALES section

### ISSUE THREAD

**Issue by k1b0rg** [SteamDatabase/steamdb.info#616]
Good day!
Recently, not all games with a discount are displayed in the SALES section.
For example:
DCS: MiG-21bis (https://steamdb.info/app/316964/info/) has a 50% discount until April 29, 2019
but in the sales (https://steamdb.info/sales/, with default filter settings) section it is not displayed

but, if filter by type set "DLC only" - the game (DCS: MiG-21bis ) is displayed

If this is not an error, how can you get absolutely all discounts in one request?

**Comment by xPaw** [comment]
DLC have been hidden from default view for years.
