### ISSUE TITLE
From #617 I get 429s when loading Killing Floors 2 items

### ISSUE THREAD

**Issue by SuperSandro2000** [SteamDatabase/steamdb.info#619]
When I try to load https://steamdb.info/app/232090/items/ I get 429 after arround 3/4 of the requests.

When I open the request manual I get this from cloudflare https://i.imgur.com/hRSHopA.png

Here is a log from Chrome 74 
[steamdb.info-1557675814750.log](https://github.com/SteamDatabase/steamdb.info/files/3170256/steamdb.info-1557675814750.log)

**Comment by xPaw** [comment]
Lazy image loading broke after I added pagination. Thanks, fixed.
