### ISSUE TITLE
somepeople are using SteamDB to buy region lock or content restrict steam game.

### ISSUE THREAD

**Issue by 964761323** [SteamDatabase/steamdb.info#620]
Yesterday, someone told me this, and i try it. Unfortunately it still works. People are using this to buy those region locked game, and adults content game via the "purches on steam" button, they are mostly kids! There are countries has law about those thing. If the goverment finds out, I'm afraid they may block steam once and for all. So please fix it.

**Comment by xPaw** [comment]
This website does not sell anything.
