### ISSUE TITLE
Sales section not including some games in default view - until you select filter

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [SteamDatabase/steamdb.info#621]
There is a bug on steamdb in the Sales section. Right now Bladeline VR is not searchable unless you choose "HTC Vive" feature filter. Suspect other games are being hidden accidentally in similar manner.

**Comment by xPaw** [comment]
That's not a bug, games with "Profile Features Limited" (low confidence metric on steamdb) are hidden when no filters are applied.

**Comment by zxsdklfhskyrvk** [comment]
Can you please explain the reasoning for a hidden, irremovable and apparently undocumented feature?  Can this just be converted to a default selection?

Or at least give a better description of this filter?  I can't see any reason the profile info for this game is any different from the others?  What parameters are relevant to the decision here?  Is this a SteamDB or a Steam choice?

**Comment by zxsdklfhskyrvk** [comment]
Can you please explain the reasoning for a hidden, irremovable and apparently undocumented feature? Can this just be converted to a default selection?

Or at least give a better description of this filter? I can't see any reason the profile info for this game is any different from the others? What parameters are relevant to the decision here? Is this a SteamDB or a Steam choice?

**Comment by zxsdklfhskyrvk** [comment]
Can you please explain the reasoning for a hidden, irremovable and apparently undocumented feature? Can this just be converted to a default selection?

Or at least give a better description of this filter? I can't see any reason the profile info for this game is any different from the others? What parameters are relevant to the decision here? Is this a SteamDB or a Steam choice?
