### ISSUE TITLE
Provide searching for games inside bundles (for identifying sales)

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [SteamDatabase/steamdb.info#623]
It would be nice to have the ability to search and filter on bundles containing **specific games**.  The default Bundle page is unusable unless you know what you are looking for.

If there is a way to identify games _included in the bundle_ that are on sale, that would be VERY helpful.  

Elsewhere, you are able to markup games that a player has in their wishlist (via the browser plugins), this seems plausible to do something similar here,  via a check of the "games" included in a bundle.  **Yes, prob another lookup, but seems possible.**

**Comment by xPaw** [comment]
App page lists which bundles the game is included in: https://steamdb.info/app/236850/subs/

**Comment by zxsdklfhskyrvk** [comment]
My goal is to locate sales of the games.  Not just be aware of what bundles they are in.

Doing this from the bundle side of things would make bundles useful/searchable.

**Comment by xPaw** [comment]
Can you elaborate on what exactly you want to search for?

**Comment by enchained** [comment]
@xPaw I'm not sure what @zxsdklfhskyrvk meant exactly, but I can agree that bundles with games that are on sale need more discoverability, cause they can save a lot, but currently you can properly see those deals either by going on every game's Steam page from the SteamDB Sales page, or you try to go through the SteamDB Bundles page (the latter took an insane amount of hours for me during the Summer sale, so I'm interested in any alternatives for bundle discovery).

I think the main issue with the current Bundles page is that there's no way to filter anything, there's just sorting and search, and it's a really long list. So after my deep dive into that list, I came up with a few ideas, I hope you'd find some of them useful and implementable.

Proposed filters:
- Show only those that have wishlisted games.
- Show only unowned "Must purchase as set" - to browse only those - would work great with discount sorting and wishlist filter.
- Show only giftable.
- Show only recently increased discounts (in the last n days/month?). I'm thinking of something similar to blue discounts on the Sales page.
- Hide "Must purchase as set" if you already own 1+ from it.
- Hide bundles with 0% discount (advanced: filter with a minimum discount field).
- Hide owned bundles (by total number of subs vs owned subs).
- Hide currently not accessible bundles. There are A LOT (feels like 50%ish if not more) of cases for me when a link to bundle redirects to the Steam front page (RU region), but works just fine with US VPN, and even shows up in Steam search with personalised price without any VPN, so it's not deleted, just hidden from purchase. Usually that happens on sales (maybe publishers don't want double discounts in cheaper regions?). And it's not constant, I couldn't open Resident Evil/Biohazard Collector's Pack on earlier sale, but could access it during the Summer sale and between the sales. I think the browser extension could detect immediate availability by doing requests, if needed I could try to reproduce and compare requests via userscript or something. The availability data should be individual for each user and could be cached for 24h for faster loading.

If we need to go deeper, there's an idea to add specific bundles to wishlist/ignore list and filter by those, maybe even alert on sales, but this requires the user to be registered for that data storage.

Proposed sorting:
- Percentage of owned (the more you're already own, the more you'll save with the rest).
- Last updated or even last discount change, to detect new discounts and new game addition.



As for the bundles tab (like https://steamdb.info/sub/25586/bundles/ and https://steamdb.info/app/221040/subs/) - it could include the total and owned number of subs, like the main Bundles page already does.

Also, from the side of the SteamDB Sales page, there could be an indication if game on sale also has bundles, so you possibly could save more and should look into that. At least an icon with link to bundles page of the game, or even small popup on icon hover showing clickable bundle names with discount percentage and an icon of bundle type.

I am also not sure I understand the meaning of green and blue highlight on the Bundles page, could you please explain it, and add that to the page's legend?

**Comment by xPaw** [comment]
I added some features on the bundles page, take a look.

**Comment by enchained** [comment]
@xPaw Thank you so much, you added most of the filters so quickly, and it seems to work great! I'll continue testing it during the future sales, and will post about the new features on reddit and steamgifts sometime soon. 

Also the most obvious and powerful filter came to mind:
a filter to show only bundles which internal apps are currently on some sale. This could work wonders when applied together with current wishlist filter.

**Comment by xPaw** [comment]
So you mean showing only bundles if anything inside of it also has discounts on their own, besides the base bundle discount?

**Comment by enchained** [comment]
> So you mean showing only bundles if anything inside of it also has discounts on their own, besides the base bundle discount?

@xPaw yes, as a way to discover a deeper discount on temporary sales. Oh, I see that you've added it already. That's amazing, thank you very much!
