### ISSUE TITLE
Request: ability to filter/show whether system requirements are met.

### ISSUE THREAD

**Issue by saspelund** [SteamDatabase/steamdb.info#630]
I have a cheap laptop that I carry around with me and would like to be able to see which of my steam games my laptop can handle. The information is available online but not in an easy-to-view format. This would help me choose my next game to play (I often browse for a while and then go back to an old game or just turn my laptop off, kinda like netflix).

Using steamdb.info, I can sort all my steam games (70+ of which 50+ are unplayed) by rating. I can then go to CYRI and see if the top unplayed game (e.g. BattleBlock Theater) can run on my laptop, but it tells me that it can't because it needs a GeForce 8400 while I have Intel HD 3000. But then I go to Passmark benchmarks (I find this a good tool for summing up all the gpu/cpu specs into a single number that doesn't care about "dedicated video ram") and it tells me that my gpu score is 3x what is needed at minimum. Looking at the store page for this game has the same requirement info so it might hopefully be available in the API.

Would there be a way to combine these three sets of information (or variations thereof) and be able to help guide which game I should try next on my laptop? My thinking is to be able to input your basic specs (def cpu, gpu, ram, os, and maybe even trackpad vs mouse?), and steamdb would tell you whether your computer can handle each one (yes/no or shading from very green for way above recommended, yellow for meets recommended, orange for meets minimum, redder as you get further from the min).

I can see lots of people who use free/cheap game forums with low end systems benefiting from this functionality. I have very little experience with coding so if this is not feasible, that's understandable, I just thought it might be a cool idea and hopefully easy to implement for us low-end gamers! 

Thanks!!

And I really love the site for all its other great tools!

**Comment by xPaw** [comment]
There are other sites for this.

**Comment by saspelund** [comment]
Oh cool! Could you direct me to a site that has my whole list of steam games and can tell me which ones I can run on my laptop? Thanks!!
