### ISSUE TITLE
[Feature Request] API for SteamDB data (manifest history , depot key etc.)

### ISSUE THREAD

**Issue by Jack-Myth** [SteamDatabase/steamdb.info#631]
I want to get some data(manifest history) from steamdb, but I can't find any API for it. I also try to analyse the web page but I can't get anything except the page that contain the "Just a moment". So I hope there can have some API to get the data that only held by SteamDB, It will be very useful.

**Comment by xPaw** [comment]
We have no plans for an API. Use steamkit to get the info you need.
