### ISSUE TITLE
SteamDB Sales "Ends In" Script is broken with most of Entries don't have time...

### ISSUE THREAD

**Issue by Black3ird** [SteamDatabase/steamdb.info#632]
Dear Sir,

Thank you for your great Service so that https://steamdb.info/sales/ is the **most** visited page in my browser to keep track of sales instead of other sites offering similar functionality. But upon checking that page to see what's on Sale at Steam last week, out of close to ~1000 titles only ~50 of them **right now** are having "Ends In" information whereas actual Steam Pages show the ending **hours** but SteamDB fails to deliver that crucial piece of data like it used to be in the past.

I've been using SteamDB Sales _just_ because of the great Sorting Options you provided mostly relying on "Ends In" and now all becomes not functional at all as without "Ends In", I'll have to check hundreds of titles by hand to see if their Discounts ends few hours later. But when it was functioning it was easy to deal **only that DAY**'s discounts relying on "Ends In" without Information mess.

This was something you intentionally applied during Big Steam Sales so that "Ends In" Column was entirely removed until the end of Sale but there's no such Sale right now and no reason for it to not show other than some _malfunction_ on the Page Script failing to fetch the required timing Data. Hoping this will get fixed soon before I've begin to search _alternative_ solutions as to suggest others the same.

Your work is much appreciated and hoping a "Quick Fix" from you until next week.

Best Regards.

PS: This is how it looks like right now (All in One HTML from Chrome) https://gofile.io/?c=pOtygT

**Comment by xPaw** [comment]
I broke that yesterday, will fix and re-crawl.
