### ISSUE TITLE
Cloudflare blocking blog RSS

### ISSUE THREAD

**Issue by CorruptCommit** [SteamDatabase/steamdb.info#633]
Greetings,

I just noticed that my RSS reader ([Nextcloud news][0]) is be blocked by Cloudflare since late July, :rofl:.  I can only guess that the Nextcloud server's IP got caught up in some sort of greylist.  The server gets a 503 reply and loads Cloudflare's `Checking your browser before accessing` page.  Testing with Firefox configured to proxy through the server, I was able to access the RSS feed after completing Cloudflare's browser check.  Unfortunately, curl and the RSS reader on the server gets immediately gets greylisted again.

Any ideas or chance y'all would consider disabling Cloudflare for the RSS feed?

[0]: https://github.com/nextcloud/news

**Comment by SuperSandro2000** [comment]
How often do you check the rss feed? Did you manually try to load the URL and complete the challenge on the same IP?

**Comment by xPaw** [comment]
What's your server hoster/ip?
