### ISSUE TITLE
Provide VR-centric charts

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [SteamDatabase/steamdb.info#634]
Interested in "Most played", Trending, Popular and Hot charts.  Maybe just provide a link to a dedicated page via the homepage with a "VR Charts here" link

Not sure if data for this is exposed, but it would be great to breakout top VR (supported) game usage, alongside flat games.  Since some games support both flat and VR,  not sure how to deal with that.   I have to imagine you could just filter the data for the existing charts (if it covers all gameplays).

To avoid this "VR only" could be used for the filter - but that would cut out what is potentially some of the largest VR games (No Mans Sky, skyrim).  So I'd prefer to use "VR Supported" instead.

The idea here is to show what VR potential there is.  It is a fraction of regular usage, and this would expose top game selections to potential players.

**Comment by xPaw** [comment]
I have no interest in adding this specifically for VR.

Best you can do is view VR tag: https://steamdb.info/tags/?tagid=21978
