### ISSUE TITLE
Concurrent Players Charts fail to display when category is set.

### ISSUE THREAD

**Issue by zths** [SteamDatabase/steamdb.info#635]
Just see in this link : https://steamdb.info/graph/?category=1

This page will cause Javascript error: "Uncaught RangeError: Maximum call stack size exceeded" on Chome.
And in Mircosoft Egde will loop like forever and eat about ~2Gb of memory.

Seem is #table-apps > tbody has a lot of  "tr" ( About : 135756 on my count, is Too much), and "jQuey.find" can't handle that much child elms......

![image](https://user-images.githubusercontent.com/1347403/66409570-5ad25700-ea23-11e9-8102-ade8b39af766.png)

![image](https://user-images.githubusercontent.com/1347403/66410037-067ba700-ea24-11e9-9f10-e241f576f2d9.png)

**Comment by xPaw** [comment]
That was a bug in the filter query, fixed now.
