### ISSUE TITLE
The footer overflow the left menu when the table only have a few entries

### ISSUE THREAD

**Issue by Ciriak** [SteamDatabase/steamdb.info#637]
Example :

(History Tab is hidden by the footer)

![image](https://user-images.githubusercontent.com/9463585/67574061-0674ea00-f73a-11e9-8e78-b3273a149b62.png)

Page :
https://steamdb.info/app/1171460/dlc/

**Comment by xPaw** [comment]
Fixed, and did some other improvements as well.
