### ISSUE TITLE
Devil May Cry 5

### ISSUE THREAD

**Issue by Volp34** [SteamDatabase/steamdb.info#638]
Hello, I've discovered a mistake.   Devil may cry 5 does not show the price of the game.
![Ekran Alıntdısı](https://user-images.githubusercontent.com/57332774/68093511-4d37b200-fea7-11e9-8f47-fe386eac91d6.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/57332774/68093512-4dd04880-fea7-11e9-9c5b-922537bbcb81.PNG)

**Comment by ymgve** [comment]
That's because the base game has no price. You can only buy it as part of a bundle, and your second screenshot is of such a bundle.

**Comment by Volp34** [comment]
![Ekran Alınt2321121212121ısı](https://user-images.githubusercontent.com/57332774/68094167-18c7f400-feaf-11e9-87a3-90cec984f239.PNG)
Are you serious ?

**Comment by Volp34** [comment]
The value of the account appears to be low because it does not calculate this game.

**Comment by ymgve** [comment]
https://store.steampowered.com/app/601150/Devil_May_Cry_5/

All products on that page are bundles. You can not buy the game outside the bundles, and therefore it does not have a price.

**Comment by xPaw** [comment]
Even Valve struggles to show the price for this game in search and other places.
