### ISSUE TITLE
Please Stop Including EVERY Sale into "Will Not Show Ending Time" Procedure...

### ISSUE THREAD

**Issue by Black3ird** [SteamDatabase/steamdb.info#640]
Dear Sir,

SteamDB has a Habit of (kind of bad but understandable as will explain) **Removing** "Ending Date" of game sales on https://steamdb.info/sales/ page which is most likely to avoid Overload during **_Real Steam Sales_** that lasts at Least a WEEK or better Two Weeks like Summer and Winter Sales where almost half of Steam Catalogue (nearing ~19,000 titles) being on sale. This is somewhat inconvenient Only for the stupid Game Devs and Publishers who decided to Opt Out of Big Sale but put their games on Sale in the Middle of a bigger Sale which becomes their loss to be noticed.

But I've just noticed that you REMOVED Ending dates for Singles' Day Sale (Unheard of Sale of any year due Google) which seems to began at ~10th November which means it's a freaking "2 DAY SALE" with much much lesser titles being on Sale compared to "Real Sales" which merged with ongoing other Sales of Steam such WeekLong + WarChild + Activision + Warner Bros Sales altogether resulting  few thousand titles being on Sale with no real justification to remove those important Ending Dates from https://steamdb.info/sales/ page.

If you don't noticed yet, there's ALWAYS some kind of Sale on Steam on every week or day so that extending your Logic to remove Ending Dates, you should remove Ending Dates for good from now on since this seems to be a very very big problem for your system so that you felt need to remove dates even for this tiny speck of an Sale that's  called Singles' Day Sale which is most likely to not happen next year like most of those one time Weekend Steam Sales of the past you can Google.

Sorry to bother you but "Ending Date" is one of the very rare Features that distinct you from IsThereAnyDeal and without it, what you offer becomes irrelevant as ITAD offers much more complex searches and features that SteamDB doesn't possess when it comes to Sales to find the right games to buy with one's limited gaming budget.  "Ending Date" maybe a trivial feature for you but it's very "Essential" for those with limitations so to know if they can buy the game NOW or WAIT for at least a week if they're getting paid Weekly instead of Monthly.

Since No One wants to pay for a game that will be on sale for the next 2 weeks right now, your decision to remove "Ending Dates" makes "Going to Expire Tomorrow" Deal same as "You can wait another Week" Deal so that Buyer can make very wrong Purchase Decisions with their budget thanks to such logic behind the removed "Ending Dates" almost on every tiny sale. It's almost SteamDB is asking "Don't use us during Sales" as we can't overcome our difficulties so that we CRIPPLE our site instead. 

Don't get it wrong as your efforts are much appreciated but small things like these are also indications to seek alternatives (or develop workarounds) to get away from SteamDB Sales Page and if you wanted that, you never have put the page in the first place. So sincerely please; Stop including every Non-Big Sale in this "Remove Ending Date" Procedure of yours as it really was a cold shower to see such change while trying to get last weeks Weekend Deals now "Gone" (blended) into this indistinctive state of https://steamdb.info/sales/ page.

Best Regards.

**Comment by xPaw** [comment]
You can take these issues less personally.

The 'ends in' was being hidden when there's over 5000 items have discounts which I have now removed.
