### ISSUE TITLE
Notification that appears on login, "Failed to load game data from Steam. Are you logged on the Steam Store?"

### ISSUE THREAD

**Issue by saladofstones** [SteamDatabase/steamdb.info#641]
"Failed to load game data from Steam.
Are you logged on the Steam Store?"

Appears everytime on login. I have done all the obvious things.
1.) Removing then reinstalling the plug-in
2.) Logging out, and back into, the steam store
3.) Checking all of my privacy settings.

I've seen the issue raised before by other users, but with no solution found.

**Comment by xPaw** [comment]
There's no one solution to this.

Make sure your third party cookies allow access to steam store.

**Comment by saladofstones** [comment]
How can I check that?
