### ISSUE TITLE
Robot verification page displays an exception [mainland China]

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamdb.info#642]
![verification](https://user-images.githubusercontent.com/9050713/69479892-68119c80-0e3d-11ea-8d1a-47fc5cc0db15.png)
Since Cloudflare is not using Google reCAPTCHA in mainland China, I am not sure if this issue is extensive.

https://steamdb.info/cdn-cgi/scripts/baidu.challenge.js

**Comment by xPaw** [comment]
I removed the custom page.
