### ISSUE TITLE
Tag translations got mingled

### ISSUE THREAD

**Issue by taylankasap** [SteamDatabase/steamdb.info#643]
Suddenly all tag translations got mingled/mixed. Before this happened all tags were in English.

[Tags page](https://steamdb.info/tags/)
![image](https://user-images.githubusercontent.com/4192479/69670711-8da0df00-10a5-11ea-9fcc-3fb1c1348139.png)
Tags dropdown in [sales page](https://steamdb.info/sales/)
![image](https://user-images.githubusercontent.com/4192479/69670739-9c879180-10a5-11ea-8ccc-4d1d2e59e852.png)

This happened right after I installed the extension but I don't think it's related since same thing happens both in incognito and on different browsers.

**Comment by xPaw** [comment]
Valve with their broken ass store pages.

**Comment by xPaw** [comment]
Hopefully fixed them all, if you see any wrong ones, do tell.
