### ISSUE TITLE
Add 'Daily Change' to 'Upcoming'

### ISSUE THREAD

**Issue by babon** [SteamDatabase/steamdb.info#646]
Add 'Daily Change' to the 'Upcoming' page, and allow so sort by it.
Would be immensely useful as a game developer to see which upcoming store pages are growing the fastest.
Example:
![loadtqt 1](https://user-images.githubusercontent.com/8108813/71271003-007b3e00-2364-11ea-9411-32b5e17a3467.jpg)

**Comment by xPaw** [comment]
Done.
