### ISSUE TITLE
Unclear what icons on the patchnotes screen mean

### ISSUE THREAD

**Issue by anowlcalledjosh** [SteamDatabase/steamdb.info#647]
These two icons are present as columns in the patchnotes table:

![image](https://user-images.githubusercontent.com/9433472/71315405-71018800-2454-11ea-85e8-8524c2108805.png)

but there's nothing to explain what they actually mean – no title, no link, no nothing.

- what do they mean?
- please can you add at least a `title` which explains that?

**Comment by SinZ163** [comment]
while the header doesn't have it, each icon in the table does.
Check out dota where it has the most patchnotes https://steamdb.info/patchnotes/?appid=570

![](https://i.imgur.com/KeTktKz.png)
![](https://i.imgur.com/yQeaAcD.png)
![](https://i.imgur.com/bdw1D8P.png)

**Comment by anowlcalledjosh** [comment]
> while the header doesn't have it, each icon in the table does

That doesn't help much when none of the rows in the table have that icon :upside_down_face:
