### ISSUE TITLE
Add detailed platform support metadata

### ISSUE THREAD

**Issue by g2p** [SteamDatabase/steamdb.info#649]
See this announcement:
https://steamcommunity.com/groups/steamworks/announcements/detail/3632639303428097613

For example, macOS Catalina apps need to be 64-bit and notarized.
Currently, the only way to check this info is to browse the store with a Catalina user-agent.

**Comment by g2p** [comment]
The metadata seems to be in the osextended key:
https://steamdb.info/app/224760/info/

**Comment by xPaw** [comment]
... add it where? It is in `osextended` as you pointed it out.

**Comment by g2p** [comment]
Search filters would be convenient.

**Comment by g2p** [comment]
As far as I can tell
- osarch=64 maps to 64-bit only windows apps.
- osextended is a coma-separated list that needs to contain macos64 for the app to be installable in Catalina.
- macosnotarized can also be set, but is not a requirement.

So my feature request would be for a facet/filter that makes for a more user-friendly version of this search:
https://steamdb.info/search/?a=app_keynames&type=1&keyname=458&operator=1&keyvalue=macos64

**Comment by xPaw** [comment]
I've added 64bit/notarized to instant search.
