### ISSUE TITLE
Feature request (website): ability to filter by amount of user reviews

### ISSUE THREAD

**Issue by funnelfactory** [SteamDatabase/steamdb.info#650]
Hello.

I would like to request a feature for the website: the ability to filter by amount of user reviews. So, for example, in addition to using other filters like price, discount, and rating, I would also like to limit the results by filtering a minimum amount of user reviews. For instance, if I only wanted to see items that have at least 100 user reviews.

Thanks and keep up the great work.

**Comment by xPaw** [comment]
Our rating formula already accommodates the number of reviews in it, so there's hardly any reason to have separate filter for it.
