### ISSUE TITLE
Add software applications to "Top Rated" list

### ISSUE THREAD

**Issue by TiEul** [SteamDatabase/steamdb.info#651]
Hey,

would be cool to also see software apps on this list here (possibly as an option if you don't like having apps in there?):

https://steamdb.info/stats/gameratings/

Do note that I am on the Wallpaper Engine development team and definitely not a "neutral" user. That said, thanks for the great website, your currency overview is far better than the tools that Valve provides.

**Comment by xPaw** [comment]
Sure: https://steamdb.info/stats/gameratings/?all_types
