### ISSUE TITLE
Sales - Discount and Rating settings not saved

### ISSUE THREAD

**Issue by Bobogoobo** [SteamDatabase/steamdb.info#652]
My settings for Discount and Rating on /sales/ seem to reset almost every time I use the page, whereas the checkbox states, at least, are saved (unless I'm using the defaults, not sure. I have shown blue, show green, and hide owned checked). I don't always notice that they've reset and feel like I miss sales sometimes.

Thank you for the extremely helpful tool!

**Comment by xPaw** [comment]
They're not saved because these are filtered through the server, where as checkboxes are applied on the page (stored in localstorage).

You could bookmark page with discount/rating set to what you want.

**Comment by Bobogoobo** [comment]
Fair enough, bookmarking works for me. Hadn't thought of that. Thanks!

**Comment by xPaw** [comment]
Gonna close because they are persisted through the url.
