### ISSUE TITLE
Sales - DLC hidden with no filters applied

### ISSUE THREAD

**Issue by Bobogoobo** [SteamDatabase/steamdb.info#653]
On /sales/, DLC on sale is hidden even when nothing is selected for "Filter by type" (i.e. the top option is selected). The expected behavior is that nothing at all is filtered out. If you'd like to keep DLC filtered out by default, then the default option should be renamed to make that clear. Or there could be a notice above the table that DLC is hidden. After using the page for months I only noticed recently that DLC is hidden by default, so I must've missed lots of sales.

Thank you!

**Comment by pizzahut2** [comment]
Does "DLC for owned games" work? Doesn't for me, but could be because my profile is usually friends-only. Normally that's not an issue because I have the browser extension installed.

https://steamdb.info/sales/?min_discount=0&min_rating=0&displayOnly=OwnedGamesDLC

**Comment by xPaw** [comment]
> but could be because my profile is usually friends-only. Normally that's not an issue because I have the browser extension installed.

Your games have to be synced via the API, so your games list should be publicly visible.
