### ISSUE TITLE
Control Sums for files

### ISSUE THREAD

**Issue by 1vanK** [SteamDatabase/steamdb.info#654]
I was looking on the site for a way to find checksums of files and compare with what I have, but could not find. Is there any chance to expect the appearance of checksums on the site? (I think pages like this https://steamdb.info/depot/570941/ is good place for it). SHA1 can be extracted from maniests

**Comment by xPaw** [comment]
> I was looking on the site for a way to find checksums of files and compare with what I have

Do verify content in Steam client. If you need to verify files that you don't have access to on Steam, that sounds like piracy.

**Comment by 1vanK** [comment]
I'm not going to make excuses or something like that, because there are situations when I need an old version of some game for speedrun. This is not about me, but about the functionality of the site.

**Comment by xPaw** [comment]
We don't display files for old versions anyway.

**Comment by 1vanK** [comment]
If so, then this is a flaw
