### ISSUE TITLE
Script Generated from https://steamdb.info/freepackages/ fails to work in Google Chrome 

### ISSUE THREAD

**Issue by gjdunga** [SteamDatabase/steamdb.info#655]
Attempting to use the https://steamdb.info/freepackages/  Script.

While using Windows 10 (10941.172)
While using Version 80.0.3987.163 (Official Build) (64-bit) 

Unable to use the script... 
Error Message as follows: 
Refused to load the script '' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://steamstore-a.akamaihd.net/ https://steamstore-a.akamaihd.net/ *.google-analytics.com https://www.gstatic.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

![Annotation 2020-04-07 084111](https://user-images.githubusercontent.com/527080/78685957-b33dc080-78af-11ea-8794-7d0358d6a3b6.png)

Microsoft Edge Microsoft Edge 44.19041.1.0  does not have the same issues, but I would really, REALLY prefer not to use Edge...

**Comment by xPaw** [comment]
Works fine here, try disabling all your extensions. The errors on your screenshot are unrelated.
