### ISSUE TITLE
Discounted price rounding

### ISSUE THREAD

**Issue by Martios** [SteamDatabase/steamdb.info#656]
I have seen an issue with rounding, let me give an example:

Dragon's Dogma: Dark Arisen
lowest price is R$ 22,49 at -70% | -70% | R$ 22,50

So the current price is $22.50 and this is the lowest price recorded ever, but possibly due to rounding in a previous sale (perhaps due to currency conversions), it is not marked with a blue discount tag because at some point it was $22.49.

My suggestion is to add a tolerance of 5 cents when deciding if the current price is the lowest price ever, if the current price is within 5 cents of the lowest record then apply the blue tag and omit the lowest price ever.

**Comment by xPaw** [comment]
Blue is for new lowest discounts, green is for matching ones (for up to 20 cents), so this game having a green discount is correct.
