### ISSUE TITLE
Can't submitting tokens to SteamDB with Token Dumper

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamdb.info#657]
```
[!] Update check failed: Response status code does not indicate success: 403 (Forbidden).
[!] Your submission may fail if you continue with the dumping.
```
This problem is because when users in Mainland China visit steamdb.info, they are always asked to verify whether they are human.
![1](https://user-images.githubusercontent.com/9050713/80445733-91cc7380-8947-11ea-845f-50f7309bd181.png)
So when Token Dumper was submitting tokens to SteamDB, it will fail.

And I tried using [NetchX/Netch](https://github.com/NetchX/Netch) to forward my network traffic through the proxy server.
But it doesn't seem to work? I use "Bypass LAN (TUN-TAP)" settings.

**Comment by wordlesswind** [comment]
Oh thank God, I finally found a proxy server that does not require Cloudflare verification.

[error.html.zip](https://github.com/SteamDatabase/steamdb.info/files/4543380/error.html.zip)

Then I copied out the output HTML file information from Token Dumper, hope I can help you.

**Comment by xPaw** [comment]
Unfortunately I have firewall configured for some Chinese networks because too much abuse comes from there.

**Comment by wordlesswind** [comment]
> Unfortunately I have firewall configured for some Chinese networks because too much abuse comes from there.

Yes! I fully understand your behavior.

So my point is to add prompt information to avoid the player running the program without knowing this message.

For example: Sorry, your request has been intercepted due to abuse on your IP address. Please try to use a proxy server.

Thanks.

**Comment by xPaw** [comment]
Well, that's what the update check is secretly for, to check whether connectivity works or not.
