### ISSUE TITLE
Minimum players filter

### ISSUE THREAD

**Issue by sanchitcop19** [SteamDatabase/steamdb.info#658]
Hi there! First off, absolutely excellent job on the website I can't believe I lived so long without having known about it haha. 

Would it be possible to include a minimum players/reviews filter for the sales page? There are tons of games, but I (and, I'm hoping others) only like to play the ones that have been tested thoroughly by gamers before me haha, so only popular ones. 

Thanks!

**Comment by xPaw** [comment]
Filtering by amount of players only works for _popular_ multiplayer games. Singleplayer games will have a fast drop off of players making this somewhat useless.

Filtering by rating and amount of reviews should accomplish this nicely.

**Comment by sanchitcop19** [comment]
Just saw the feature live, thank you so much!
