### ISSUE TITLE
Add "last played" as alternative for (removed) "last online"

### ISSUE THREAD

**Issue by ProfChaosss** [SteamDatabase/steamdb.info#659]
#Feature Request 
In February this year stem unfortunately removed the "last online" information to be visible for non-friends, an information you showed at the profile summary ("get disappointed in your live"). 
Maybe it is possible to work around this new restrictions by using the "last played" information which is still visible (at least on public profiles i.e. [my profile](https://steamcommunity.com/profiles/76561198098208008)).

**Comment by xPaw** [comment]
The API we are using has no dates in it, so we can't get that.
