### ISSUE TITLE
TokenDumper exists with "Failed to create CoreCLR, HRESULT: 0x80004005"

### ISSUE THREAD

**Issue by marvinside** [SteamDatabase/steamdb.info#660]
Could not find a repository for the Token-Dumper, so reporting it here.

Nothing more than this message:

```
$ ./SteamTokenDumper 
Failed to create CoreCLR, HRESULT: 0x80004005
```

```
$ uname -r
Linux HOSTNAME 5.3.0-7625-generic #27~1576774560~19.10~f432cd8-Ubuntu SMP Thu Dec 19 20:35:37 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

I'm not sure if this might help, but i ran strace. Here's the log:
[log_SteamTokenDumper.txt](https://github.com/SteamDatabase/steamdb.info/files/4568659/log_SteamTokenDumper.txt)

**Comment by xPaw** [comment]
This appears to be some kind of generic .NET Core issue, can't really help with that.

**Comment by marvinside** [comment]
Okay, will use the Windows version as soon as I'm on a Windows PC.

Keep up the good work, really cool Idea :+1:

**Comment by xPaw** [comment]
This appears to have been caused by publishing incorrectly. I uploaded a new build which should work.
