### ISSUE TITLE
Pricing discrepancies between Steam and Steamdb

### ISSUE THREAD

**Issue by didactw** [SteamDatabase/steamdb.info#661]
I have been noticing this for quite a few games now, but it seems like some prices are not updated (higher) on steamdb when compared to the steam store?
This is the price on Steam:
![image](https://user-images.githubusercontent.com/64904140/81174918-ce503d00-8fe1-11ea-8e8d-67cb953f1a98.png)
This is the price on steamdb:
![image](https://user-images.githubusercontent.com/64904140/81175012-fdff4500-8fe1-11ea-8190-ddc817570746.png)
Is there a reason why the currently 20% discounted price is not showing on steamdb? Makes it hard to know when it is a deal to get a game.

**Comment by xPaw** [comment]
You have a loalty discount or something, this game is not on sale.

![image](https://user-images.githubusercontent.com/613331/81175484-4b60bf80-8fac-11ea-976c-91f460583902.png)
