### ISSUE TITLE
Pull Steam's Simplified Chinese Strings

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamdb.info#662]
Hello, xPaw

I found that in the [May 5th update](https://github.com/SteamDatabase/SteamTracking/blob/e128aa21e119a8e2e6b91600ff8d09282f663fad/ClientManifest/steam_client_publicbeta_win32#L108-L115), the Simplified Chinese text file has one more line of text than the English text file.

> "SteamChina_Overlay_DurationControl_ExitSoon_Night"	"未满18周岁的用户在22点到次日8点\n无法进入游戏，请您注意休息。"
"[english]SteamChina_Overlay_DurationControl_ExitSoon_Night"	"Players under 18 can't play this game between 10PM\nand 8AM the following day. Please take a break."

Interestingly, there is no line of text on [overlay_english.txt](https://github.com/SteamDatabase/SteamTracking/blob/70026dedf3858bf4f9b752bbfc1762536b768860/ClientExtracted/resource/overlay_english.txt#L256-L262) [steam_client_publicbeta_win32/strings_en_all.zip.f2fdf51e297c2b2722ed133bc5667a8c8a71794b](http://client-download.steampowered.com/client/strings_en_all.zip.f2fdf51e297c2b2722ed133bc5667a8c8a71794b)

So I was thinking, maybe Perfect World has some autonomy for SteamChina?
Some updates may not appear first on Steam.

**Comment by xPaw** [comment]
I ignored non-english files from the tracker before, added them now.

https://github.com/SteamDatabase/SteamTracking/blob/9d961e722f2466f4142e85b4b18e63ad1671a608/ClientExtracted/resource/overlay_schinese.txt#L449
