### ISSUE TITLE
Loading "all" entries on gameratings will freeze the browser

### ISSUE THREAD

**Issue by Zarthus** [SteamDatabase/steamdb.info#664]
https://steamdb.info/stats/gameratings/?all

![image](https://user-images.githubusercontent.com/3660408/81502478-83367280-92de-11ea-89c9-d3b14e2be81e.png)

Understandably so, because it probably tries to load 35k entries.
Maybe "all" should not be an option?

**Comment by xPaw** [comment]
That table is basically the worst case scenario, yeah. Not really worth investing time into making it more performant though (e.g. sales has the fixes so it doesn't slow down this much).

I added more length options if you want a longer table.
