### ISSUE TITLE
"Please do not crawl SteamDB" message keeps popping up

### ISSUE THREAD

**Issue by Dvvarf** [SteamDatabase/steamdb.info#666]
Hello!

Lately this message keeps popping up on the main site:
> Please do not crawl SteamDB, get the data you want from Steam directly. SteamDB is a community website that does not make money.

There is a piece of JS like this (paraphrasing from minified code):
`if (navigator.webdriver) alert("Please do not crawl SteamDB, get the data you want from Steam directly. SteamDB is a community website that does not make money.")`

I totally get (and support) the rationale behind the message, but navigator.webdriver flag is set in Chrome when it's launched with innocuous `--remote-debugging-port` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver)) argument. For me, for example, it's always enabled and getting the message on every page is rather inconvenient...

Maybe there is some way to fix this? Besides using different browser or dedicated browser instance without the debug flag.

**Comment by DidierLoiseau** [comment]
FYI I also noticed a similar issue as I had disabled the referer in Firefox.

**Comment by Louis2747** [comment]
for anyone else finding nothing but this in the future `user_pref("network.http.referer.spoofSource", true);`        caused this for me
