### ISSUE TITLE
'Prices' column  - natural sort order instead of alphabetical when in descending order

### ISSUE THREAD

**Issue by darkred** [SteamDatabase/steamdb.info#667]
I've noticed that the 'Prices' column sorting doesn't work as expected when in descending order: 
**the prices are sorted in alphabetical instead of natural order**.
Note: the sorting works ok in ascending order.

Check the screenshot example below, taken from https://steamdb.info/upcoming/ *(click the "Price" column header twice to sort in descending order)*. The sorting is done as if the price numbers were text strings. Especially notice:
- the `0,79€` price which appears 4th, after `8,49€`, instead of the bottom of the list
(it seems like its leading `0,` is ignored, and the `74` decimal part is taken into account), and
- the price `39,99€` is wrongly listed in the middle of the list, after `3,99€`, while it should be listed on top of the list

<details>
<summary>Screenshot (click to expand)</summary>

https://steamdb.info/upcoming/

![2020-05-28_185308](https://user-images.githubusercontent.com/723651/83164214-a0f43c00-a114-11ea-82e5-3cceeff31094.jpg)
</details>

Also, see this comparison mockup (current sorting vs expected) :
![2020-05-28_184539](https://user-images.githubusercontent.com/723651/83163255-82417580-a113-11ea-903a-629803e68377.jpg)  ![2020-05-28_184522](https://user-images.githubusercontent.com/723651/83163249-8077b200-a113-11ea-865b-77ea37c4cf27.jpg)

**Comment by xPaw** [comment]
Fixed. It was not sorting naturally due to missing sort order on free/no price.

**Comment by darkred** [comment]
Thanks a lot for the quick response!

**Comment by darkred** [comment]
I'd also like to make a suggestion regarding the CSS applied to the "Column" price:

```css
body td:last-child {    /* or:  body td:nth-child(6) */
	text-align: left;
}
```

I find that it makes the column much easier to read:

![2020-06-25_233327](https://user-images.githubusercontent.com/723651/85792543-5f1edb80-b73c-11ea-94b2-09a3abfcc76a.jpg) ![2020-06-25_233542](https://user-images.githubusercontent.com/723651/85792694-99887880-b73c-11ea-847c-64ccf5ea0e19.jpg)
