### ISSUE TITLE
Add filter for Nvidia's GeForce Now supported games

### ISSUE THREAD

**Issue by tlenex** [SteamDatabase/steamdb.info#673]
Public input data of supported games:
https://static.nvidiagrid.net/supported-public-game-list/gfnpc.json?JSON

Entries containing `steamUrl` does exist on steam (so we can to filter out the list), the `appId` for each entry is listed at the end of the `steamUrl`.

**Comment by xPaw** [comment]
We're not going to crawl third-party services for data.

But you can filter by the cloud gaming category that Valve added: https://steamdb.info/search/?a=app&q=&type=-1&category=46
