### ISSUE TITLE
Decrypted depot files don't show checksums

### ISSUE THREAD

**Issue by wastecollector** [SteamDatabase/steamdb.info#674]
[Encrypted depot files, with checksums and file sizes](https://steamdb.info/depot/505231/) vs [decrypted, without checksums or file sizes](https://steamdb.info/depot/732/)

Hope this gets fixed quickly

**Comment by xPaw** [comment]
What is your use case that you want to see hashes?

**Comment by wastecollector** [comment]
To quickly compare specific game files

**Comment by xPaw** [comment]
Compare to what? If you have something to compare it to, you can obtain the depot manifest with hashes yourself.

**Comment by wastecollector** [comment]
That's unpractical, I don't even know what that entails, getting a Steam API key? Parsing the manifest file?

**Comment by xPaw** [comment]
Well, describe your use case properly. Why are you comparing, what are you comparing it to.

**Comment by wastecollector** [comment]
So you prefer to cut off functionality because of virtue signalling. Cool!

**Comment by SuperSandro2000** [comment]
The only use case I could come up with is that you got a file of a game you don't own and want to verify it.
