### ISSUE TITLE
SteamDB Discord server

### ISSUE THREAD

**Issue by asdf2345** [SteamDatabase/steamdb.info#675]
Due to the nature of IRC, it's hard to get help with things, for example, when the IRC client is not running, the messages during that period that the client isn't running aren't saved. So if someone responds to a question someone asked after the person that asked it logged off, it's worthless.
A Discord server would fix these issues, and for plenty of people would get rid of a useless client they barely use. A Discord server will also bring more people in than IRC will. It's in general just a better idea.

**Comment by xPaw** [comment]
No.

**Comment by asdf2345** [comment]
> No.

Why?

**Comment by Bluscream** [comment]
You can use the /r/Steam or the ArchiSteamFarm discord servers
