### ISSUE TITLE
Add filters "Hide owned WishList" & "Hide owned Ignored" in Sales Search

### ISSUE THREAD

**Issue by EstebanJoaquinIgnacio** [SteamDatabase/steamdb.info#676]
Hi. Basically it is to add those two checkboxes to be able to filter more and reduce the list to those that one does not know.

The "Hide owned games" button speeds up very well, adding these 2 would leave only those that one has not seen before.

Greetings and thanks for the page, it is very comfortable 👍 🥇 

https://steamdb.info/sales/

**Comment by xPaw** [comment]
You already can hide ignored games from extension options.

Adding another checkbox to hide wished would be confusing enough and quite niche, so I don't think I will.

**Comment by EstebanJoaquinIgnacio** [comment]
You are right about the button but now that I realize it does not work (later I do a New Issue).

It can be confusing but with the most explicit text possible "Hide owned WishList games" should suffice. (Perhaps a first-time does not understand it, but after a short time on steam it will be realized, also he / she has to first use Steam to get to use SteamDB, it would be logical). It would also be in the "Filters part", which indicates that if you select it you will hide content.
