### ISSUE TITLE
"Hide products on sales page that you are not interested in" doesn't work (Chrome)

### ISSUE THREAD

**Issue by EstebanJoaquinIgnacio** [SteamDatabase/steamdb.info#677]
Hi.

### The option **Hide** of _extension option_ doesn't work. (i only use it's in [this page](https://steamdb.info/sales/))

I saw that there is an Issue from 2 years ago with this problem, it was for an extension. Clear all my extensions (except for the SteamDB one), clear the Steamdb cache, close and open the browser but it doesn't work.

I have:
- Windows 10 Enterprice x64
- Chrome 84.0.4147.89 x64
- I'm logged into SteamDB with my Steam credentials
- I'm logged into Steam in my browser
- I'm allowing cookies (i **NOT block** the "3rd party cookies" and I have **unchecked** the "Allow all cookies" in the "Cookies and other site data" options).

 **"Highlight owned and wished products on steamdb.info" is working correctly.**

**Comment by xPaw** [comment]
Fix pushed, but may take a while for it to be fixed on the live site, as github is having some issues atm.

**Comment by EstebanJoaquinIgnacio** [comment]
Come on, then I try.

**Comment by EstebanJoaquinIgnacio** [comment]
perfect, now it works. Thank you.
