### ISSUE TITLE
Feature Request: Download Price History Chart Context for Deluxe Edition SKUs

### ISSUE THREAD

**Issue by tmangat91** [SteamDatabase/steamdb.info#683]
There currently is an option to download price history for standard edition SKUs from the chart context menu, but this option is not enabled for deluxe edition SKUs. Could this please be added?

For reference, please see _Dark Souls III_ standard edition vs. deluxe edition:

Standard: https://steamdb.info/app/374320/

![image](https://user-images.githubusercontent.com/8854783/92272868-384cf600-ee9f-11ea-9d4a-aa8ec9b57cbc.png)

Deluxe: https://steamdb.info/sub/94174/

I would greatly appreciate your help, thank you very much.

**Comment by xPaw** [comment]
Fixed.

**Comment by tmangat91** [comment]
> 
> 
> Fixed.

Thank you!
