### ISSUE TITLE
FAQ link on token dumper page broken

### ISSUE THREAD

**Issue by pointydev** [SteamDatabase/steamdb.info#685]
Hey there,

The link on [/tokendumper](https://steamdb.info/tokendumper/) that goes to the FAQ with the text `Read more about token dumper in our FAQ section` doesn't work.

Currently, it points towards relative `faq/#tokendumper` per the href, which actually goes to `https://steamdb.info/tokendumper/faq/#tokendumper`, a non-existent page. I believe it should actually be `/faq/#tokendumper`, which points towards the token dumper section of the FAQ page.

Thanks,
Elliott

**Comment by xPaw** [comment]
Fixed, thanks.
