### ISSUE TITLE
Is something "Broken" at SteamDB Server at the moment?

### ISSUE THREAD

**Issue by Black3ird** [SteamDatabase/steamdb.info#686]
Dear Sir,

Thanks for your great work, it's very appreciated. I frequently visit your SteamDB Sales page starting with https://steamdb.info/sales/?displayOnly=OwnedGamesDLC then to the games section. But today it kept "Spinning" and spinning to the Infinity... 

Then I decided to experiment a little bit with parameters explained below to get MIXED results that some page are working, some are not;

* Empty Browser Profile won't help, no extensions    
* Different Browsers won't help  
* Different Connection IP won't help, different Countries  
* All done is Isolated instances so that no Cookie etc. retention to re-Identify  

all for the above URL so that it can't be related anything about Connection Rejection for Lots of Connections in short amount of time, which is why you're using CloudFlare or similar PROTECTION that is reasonable thing to do. Then I decide to check on games and https://steamdb.info/sales/ page without any endings works. So testing for endings this time;

* https://steamdb.info/sales/ is working
* https://steamdb.info/login/ won't work  
* https://steamdb.info/search/?a=app&q=lego is working, so does all searches  
* https://steamdb.info/sales/?{ any ending } isn't working so that NONE of the filters or settings  
* Individual SteamDB Game/DLC/Package Pages have no problems  

These are all the URL and their endings that I tested so far so that I'm confused to interpret these results because SteamDB is working. I thought URL ending parser was broken but selectively it's working either. Since I can't figure out a "Workaround" to make it work, I'd like to ask you for a explanation and for possible fix if it's something Server wide...

Thanks for your time and reading.

Best Regards.

**Comment by xPaw** [comment]
The urls that are not working for you have cloudflare browser integrity check, so you are failing that for whatever reason.

Can you please copy info from this page https://steamdb.info/cdn-cgi/trace and send an email here: https://steamdb.info/faq/#how-to-contact-you
