### ISSUE TITLE
csgo_launcher_publicbeta_win32 / dota2_launcher_publicbeta_win32

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamdb.info#689]
I found that since 10.08, the CS:GO and DOTA2 launchers are no longer based on Steam Client Beta.

So csgo/dota2_publicbeta_launcher_win32 is no longer synchronized with csgo/dota2__launcher_win32, maybe they should be tracked.

http://client-download.steampowered.com/client/csgo_launcher_publicbeta_win32
http://client-download.steampowered.com/client/dota2_launcher_publicbeta_win32

**Comment by xPaw** [comment]
I don't really see a point in these.

**Comment by wordlesswind** [comment]
I tested it, and there seems to be no substantial change.

**Comment by wordlesswind** [comment]
Oh no, it seems that the new version of CSGO Launcher, Steam and Steam China can be switched by running other versions.
![Uploading CSGO.png…]()

**Comment by xPaw** [comment]
I added steamchina_publicbeta manifests.
