### ISSUE TITLE
Incorrect depot information

### ISSUE THREAD

**Issue by aienabled** [SteamDatabase/steamdb.info#690]
Hello!

One of our game's DLC depots is incorrectly reported by SteamDB:
https://steamdb.info/app/602740/depots/
as you can see SteamDB shows there are no builds and no manifest.

However, it works properly (for 3+ years) and on the Steam Partner page we see its manifest properly:
```
DepotID : 602740
ManifestGID : 5587332044809944262
Creation time : Mar 3, 2017, 3:37 am
Number of files : 105
Number of chunks : 1523
Size on Disk : 1,543,627,409 bytes (1.5 GB)
Size Compressed : 1,556,903,632 bytes (1.6 GB, 100.9%)
...
```

Regards!

**Comment by xPaw** [comment]
You're looking at the dlc page.

https://steamdb.info/app/324260/depots/
