### ISSUE TITLE
"Failed to load app hover for appid=... Report this please." in SeaMonkey v2.53.5.1 web browser.

### ISSUE THREAD

**Issue by antdude** [SteamDatabase/steamdb.info#691]
When place my mouse cursor over a game, I get this:
![Failed2LoadAppHoverForAppID](https://user-images.githubusercontent.com/998681/101995176-15d82f00-3c7d-11eb-907c-fa9f9e1d78bb.gif)
I reproduced this in two different PCs (updated 64-bit W7 HPE SP1 & Debian Jessie v8). Last week and on didn't show this issue. Firefox v83 had no problems.

Thank you for reading and hopefully fixing it soon. :)

**Comment by xPaw** [comment]
I'm not gonna support your browser, as it's based on an outdated Firefox. I will remove that alert though.

**Comment by antdude** [comment]
Thanks for removing the annoying pop-ups. However, hovering my mouse cursor over a game loses my focus by scrolling down. I can't go back to the previous spot (https://steamdb.info/sales/#sales-section-playforfree). :(

**Comment by xPaw** [comment]
Use an updated browser.
