### ISSUE TITLE
Maybe add a quick link to protondb.com on every game next to the other quick links, like Store, Hub, PCGW and patches

### ISSUE THREAD

**Issue by alx365** [SteamDatabase/steamdb.info#692]
With Valve pushing linux a lot, it would be pretty cool to add a link to protondb.com (a website where linux gamers can add reports for games, and how they run) next to the existing ones.

![image](https://user-images.githubusercontent.com/30902201/102894825-97894300-445b-11eb-8782-1c3e4201f430.png)

I'd like to have this, because I very often use steamdb to find new games or check what the lowest price was, before i check if it runs on linux.

I understand that this only caters to linux users, but so do a few programmers at Valve.

(Also, that empty space looks awkward, put something there!)

**Comment by xPaw** [comment]
No plans to add this.
